// 人教版 PEP 小学英语（三年级起点）同步数据
// 范围：三上 ~ 六下（8 册，每册 6 单元，共 48 单元）
// 说明：基于标准 PEP 课标整理；建议对照实体课本复核音标与词序。
// 字段：
//   PEP_META    册与单元结构
//   PEP_WORDS   单词 {g,term,u,w,ipa,cn,cat}
//   PEP_TEXTS   课文(Let's talk) {g,term,u,title,lines:[{role,en,cn}]}
//   PEP_PATTERNS重点句型 {g,term,u,focus,pattern,examples:[en],cn}

window.PEP_META = [
  { g:3, term:'上', label:'三年级上册', units:[
    {n:1,title:'Hello!'},{n:2,title:'Colours'},{n:3,title:'Look at me!'},
    {n:4,title:'We love animals'},{n:5,title:"Let's eat!"},{n:6,title:'Happy birthday!'} ]},
  { g:3, term:'下', label:'三年级下册', units:[
    {n:1,title:'Welcome back to school!'},{n:2,title:'My family'},{n:3,title:'At the zoo'},
    {n:4,title:'Where is my car?'},{n:5,title:'Do you like pears?'},{n:6,title:'How many?'} ]},
  { g:4, term:'上', label:'四年级上册', units:[
    {n:1,title:'My classroom'},{n:2,title:'My schoolbag'},{n:3,title:'My friends'},
    {n:4,title:'My home'},{n:5,title:"Dinner's ready"},{n:6,title:'Meet my family!'} ]},
  { g:4, term:'下', label:'四年级下册', units:[
    {n:1,title:'My school'},{n:2,title:'What time is it?'},{n:3,title:'Weather'},
    {n:4,title:'At the farm'},{n:5,title:'My clothes'},{n:6,title:'Shopping'} ]},
  { g:5, term:'上', label:'五年级上册', units:[
    {n:1,title:'What’s he like?'},{n:2,title:'My week'},{n:3,title:'What would you like?'},
    {n:4,title:'What can you do?'},{n:5,title:'There is a big bed'},{n:6,title:'In a nature park'} ]},
  { g:5, term:'下', label:'五年级下册', units:[
    {n:1,title:'This is my day'},{n:2,title:'My favourite season'},{n:3,title:'My school calendar'},
    {n:4,title:'When is Easter?'},{n:5,title:'Whose dog is it?'},{n:6,title:'Work quietly!'} ]},
  { g:6, term:'上', label:'六年级上册', units:[
    {n:1,title:'How can I get there?'},{n:2,title:'Ways to go to school'},{n:3,title:'My weekend plan'},
    {n:4,title:'I have a pen pal'},{n:5,title:'What does he do?'},{n:6,title:'How do you feel?'} ]},
  { g:6, term:'下', label:'六年级下册', units:[
    {n:1,title:'How tall are you?'},{n:2,title:'Last weekend'},{n:3,title:'Where did you go?'},
    {n:4,title:'Then and now'} ]}
];

/* ===================== 单词 ===================== */
window.PEP_WORDS = [
  {g:3,term:'上',u:1,w:'ruler',ipa:'/ˈruːlə(r)/',cn:'尺子',cat:'文具'},
  {g:3,term:'上',u:1,w:'pencil',ipa:'/ˈpensl/',cn:'铅笔',cat:'文具'},
  {g:3,term:'上',u:1,w:'eraser',ipa:'/ɪˈreɪzə(r)/',cn:'橡皮',cat:'文具'},
  {g:3,term:'上',u:1,w:'crayon',ipa:'/ˈkreɪən/',cn:'蜡笔',cat:'文具'},
  {g:3,term:'上',u:1,w:'bag',ipa:'/bæɡ/',cn:'包',cat:'文具'},
  {g:3,term:'上',u:1,w:'pen',ipa:'/pen/',cn:'钢笔',cat:'文具'},
  {g:3,term:'上',u:1,w:'book',ipa:'/bʊk/',cn:'书',cat:'文具'},
  {g:3,term:'上',u:1,w:'no',ipa:'/nəʊ/',cn:'不',cat:'其他'},
  {g:3,term:'上',u:1,w:'your',ipa:'/jɔː(r)/',cn:'你（们）的',cat:'代词'},
  {g:3,term:'上',u:2,w:'red',ipa:'/red/',cn:'红色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'green',ipa:'/ɡriːn/',cn:'绿色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'yellow',ipa:'/ˈjeləʊ/',cn:'黄色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'blue',ipa:'/bluː/',cn:'蓝色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'black',ipa:'/blæk/',cn:'黑色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'brown',ipa:'/braʊn/',cn:'棕色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'white',ipa:'/waɪt/',cn:'白色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'orange',ipa:'/ˈɒrɪndʒ/',cn:'橙色',cat:'颜色'},
  {g:3,term:'上',u:3,w:'head',ipa:'/hed/',cn:'头',cat:'身体'},
  {g:3,term:'上',u:3,w:'face',ipa:'/feɪs/',cn:'脸',cat:'身体'},
  {g:3,term:'上',u:3,w:'nose',ipa:'/nəʊz/',cn:'鼻子',cat:'身体'},
  {g:3,term:'上',u:3,w:'mouth',ipa:'/maʊθ/',cn:'嘴',cat:'身体'},
  {g:3,term:'上',u:3,w:'eye',ipa:'/aɪ/',cn:'眼睛',cat:'身体'},
  {g:3,term:'上',u:3,w:'ear',ipa:'/ɪə(r)/',cn:'耳朵',cat:'身体'},
  {g:3,term:'上',u:3,w:'arm',ipa:'/ɑːm/',cn:'胳膊',cat:'身体'},
  {g:3,term:'上',u:3,w:'hand',ipa:'/hænd/',cn:'手',cat:'身体'},
  {g:3,term:'上',u:3,w:'body',ipa:'/ˈbɒdi/',cn:'身体',cat:'身体'},
  {g:3,term:'上',u:3,w:'leg',ipa:'/leɡ/',cn:'腿',cat:'身体'},
  {g:3,term:'上',u:3,w:'foot',ipa:'/fʊt/',cn:'脚',cat:'身体'},
  {g:3,term:'上',u:4,w:'duck',ipa:'/dʌk/',cn:'鸭子',cat:'动物'},
  {g:3,term:'上',u:4,w:'pig',ipa:'/pɪɡ/',cn:'猪',cat:'动物'},
  {g:3,term:'上',u:4,w:'cat',ipa:'/kæt/',cn:'猫',cat:'动物'},
  {g:3,term:'上',u:4,w:'bear',ipa:'/beə(r)/',cn:'熊',cat:'动物'},
  {g:3,term:'上',u:4,w:'dog',ipa:'/dɒɡ/',cn:'狗',cat:'动物'},
  {g:3,term:'上',u:4,w:'elephant',ipa:'/ˈelɪfənt/',cn:'大象',cat:'动物'},
  {g:3,term:'上',u:4,w:'monkey',ipa:'/ˈmʌŋki/',cn:'猴子',cat:'动物'},
  {g:3,term:'上',u:4,w:'bird',ipa:'/bɜːd/',cn:'鸟',cat:'动物'},
  {g:3,term:'上',u:4,w:'tiger',ipa:'/ˈtaɪɡə(r)/',cn:'老虎',cat:'动物'},
  {g:3,term:'上',u:4,w:'panda',ipa:'/ˈpændə/',cn:'熊猫',cat:'动物'},
  {g:3,term:'上',u:4,w:'zoo',ipa:'/zuː/',cn:'动物园',cat:'场所'},
  {g:3,term:'上',u:5,w:'bread',ipa:'/bred/',cn:'面包',cat:'食物'},
  {g:3,term:'上',u:5,w:'juice',ipa:'/dʒuːs/',cn:'果汁',cat:'食物'},
  {g:3,term:'上',u:5,w:'egg',ipa:'/eɡ/',cn:'蛋',cat:'食物'},
  {g:3,term:'上',u:5,w:'milk',ipa:'/mɪlk/',cn:'牛奶',cat:'食物'},
  {g:3,term:'上',u:5,w:'water',ipa:'/ˈwɔːtə(r)/',cn:'水',cat:'食物'},
  {g:3,term:'上',u:5,w:'cake',ipa:'/keɪk/',cn:'蛋糕',cat:'食物'},
  {g:3,term:'上',u:5,w:'fish',ipa:'/fɪʃ/',cn:'鱼',cat:'食物'},
  {g:3,term:'上',u:5,w:'rice',ipa:'/raɪs/',cn:'米饭',cat:'食物'},
  {g:3,term:'上',u:6,w:'one',ipa:'/wʌn/',cn:'一',cat:'数字'},
  {g:3,term:'上',u:6,w:'two',ipa:'/tuː/',cn:'二',cat:'数字'},
  {g:3,term:'上',u:6,w:'three',ipa:'/θriː/',cn:'三',cat:'数字'},
  {g:3,term:'上',u:6,w:'four',ipa:'/fɔː(r)/',cn:'四',cat:'数字'},
  {g:3,term:'上',u:6,w:'five',ipa:'/faɪv/',cn:'五',cat:'数字'},
  {g:3,term:'上',u:6,w:'six',ipa:'/sɪks/',cn:'六',cat:'数字'},
  {g:3,term:'上',u:6,w:'seven',ipa:'/ˈsevn/',cn:'七',cat:'数字'},
  {g:3,term:'上',u:6,w:'eight',ipa:'/eɪt/',cn:'八',cat:'数字'},
  {g:3,term:'上',u:6,w:'nine',ipa:'/naɪn/',cn:'九',cat:'数字'},
  {g:3,term:'上',u:6,w:'ten',ipa:'/ten/',cn:'十',cat:'数字'},
  {g:3,term:'上',u:6,w:'brother',ipa:'/ˈbrʌðə(r)/',cn:'兄；弟',cat:'家庭'},
  {g:3,term:'上',u:1,w:'pencil box',ipa:'/ˈpensl bɒks/',cn:'铅笔盒',cat:'文具'},
  {g:3,term:'上',u:1,w:'hello',ipa:'/həˈləʊ/',cn:'你好',cat:'问候'},
  {g:3,term:'上',u:1,w:'hi',ipa:'/haɪ/',cn:'嗨',cat:'问候'},
  {g:3,term:'上',u:1,w:'name',ipa:'/neɪm/',cn:'名字',cat:'其他'},
  {g:3,term:'上',u:1,w:'open',ipa:'/ˈəʊpən/',cn:'打开',cat:'动作'},
  {g:3,term:'上',u:1,w:'close',ipa:'/kləʊz/',cn:'关上',cat:'动作'},
  {g:3,term:'上',u:1,w:'show',ipa:'/ʃəʊ/',cn:'展示',cat:'动作'},
  {g:3,term:'上',u:1,w:'carry',ipa:'/ˈkæri/',cn:'拿；搬',cat:'动作'},
  {g:3,term:'上',u:1,w:'school',ipa:'/skuːl/',cn:'学校',cat:'场所'},
  {g:3,term:'上',u:1,w:'goodbye',ipa:'/ˌɡʊdˈbaɪ/',cn:'再见',cat:'问候'},
  {g:3,term:'上',u:2,w:'colour',ipa:'/ˈkʌlə(r)/',cn:'颜色',cat:'颜色'},
  {g:3,term:'上',u:2,w:'mum',ipa:'/mʌm/',cn:'妈妈',cat:'家庭'},
  {g:3,term:'上',u:2,w:'OK',ipa:'/ˌəʊˈkeɪ/',cn:'好；行',cat:'其他'},
  {g:3,term:'上',u:2,w:'this',ipa:'/ðɪs/',cn:'这',cat:'代词'},
  {g:3,term:'上',u:2,w:'is',ipa:'/ɪz/',cn:'是',cat:'动词'},
  {g:3,term:'上',u:2,w:'Miss',ipa:'/mɪs/',cn:'女士',cat:'称谓'},
  {g:3,term:'上',u:2,w:'morning',ipa:'/ˈmɔːnɪŋ/',cn:'早晨',cat:'时间'},
  {g:3,term:'上',u:2,w:'afternoon',ipa:'/ˌɑːftəˈnuːn/',cn:'下午',cat:'时间'},
  {g:3,term:'上',u:2,w:'nice',ipa:'/naɪs/',cn:'高兴的',cat:'形容词'},
  {g:3,term:'上',u:3,w:'funny',ipa:'/ˈfʌni/',cn:'滑稽的',cat:'形容词'},
  {g:3,term:'上',u:3,w:'look',ipa:'/lʊk/',cn:'看',cat:'动作'},
  {g:3,term:'上',u:3,w:'make',ipa:'/meɪk/',cn:'做；制作',cat:'动作'},
  {g:3,term:'上',u:3,w:'great',ipa:'/ɡreɪt/',cn:'好极了',cat:'形容词'},
  {g:3,term:'上',u:3,w:'my',ipa:'/maɪ/',cn:'我的',cat:'代词'},
  {g:3,term:'上',u:3,w:'me',ipa:'/miː/',cn:'我',cat:'代词'},
  {g:3,term:'上',u:4,w:'what',ipa:'/wɒt/',cn:'什么',cat:'疑问'},
  {g:3,term:'上',u:4,w:'it',ipa:'/ɪt/',cn:'它',cat:'代词'},
  {g:3,term:'上',u:4,w:'fat',ipa:'/fæt/',cn:'胖的',cat:'形容词'},
  {g:3,term:'上',u:4,w:'big',ipa:'/bɪɡ/',cn:'大的',cat:'形容词'},
  {g:3,term:'上',u:4,w:'on',ipa:'/ɒn/',cn:'在…上',cat:'介词'},
  {g:3,term:'上',u:4,w:'in',ipa:'/ɪn/',cn:'在…里',cat:'介词'},
  {g:3,term:'上',u:4,w:'log',ipa:'/lɒɡ/',cn:'原木',cat:'其他'},
  {g:3,term:'上',u:4,w:'truck',ipa:'/trʌk/',cn:'卡车',cat:'其他'},
  {g:3,term:'上',u:5,w:'like',ipa:'/laɪk/',cn:'喜欢',cat:'动词'},
  {g:3,term:'上',u:5,w:'some',ipa:'/sʌm/',cn:'一些',cat:'代词'},
  {g:3,term:'上',u:5,w:'here',ipa:'/hɪə(r)/',cn:'这里',cat:'副词'},
  {g:3,term:'上',u:5,w:'have',ipa:'/hæv/',cn:'有',cat:'动词'},
  {g:3,term:'上',u:5,w:'too',ipa:'/tuː/',cn:'也',cat:'副词'},
  {g:3,term:'上',u:5,w:'eat',ipa:'/iːt/',cn:'吃',cat:'动词'},
  {g:3,term:'上',u:5,w:'drink',ipa:'/drɪŋk/',cn:'喝',cat:'动词'},
  {g:3,term:'上',u:5,w:'cut',ipa:'/kʌt/',cn:'切',cat:'动作'},
  {g:3,term:'上',u:6,w:'sister',ipa:'/ˈsɪstə(r)/',cn:'姐；妹',cat:'家庭'},
  {g:3,term:'上',u:6,w:'family',ipa:'/ˈfæməli/',cn:'家庭',cat:'家庭'},
  {g:3,term:'上',u:6,w:'father',ipa:'/ˈfɑːðə(r)/',cn:'父亲',cat:'家庭'},
  {g:3,term:'上',u:6,w:'dad',ipa:'/dæd/',cn:'爸爸',cat:'家庭'},
  {g:3,term:'上',u:6,w:'mother',ipa:'/ˈmʌðə(r)/',cn:'母亲',cat:'家庭'},
  {g:3,term:'上',u:6,w:'grandfather',ipa:'/ˈɡrænfɑːðə(r)/',cn:'祖父',cat:'家庭'},
  {g:3,term:'上',u:6,w:'grandpa',ipa:'/ɡrænpɑː/',cn:'爷爷',cat:'家庭'},
  {g:3,term:'上',u:6,w:'grandmother',ipa:'/ˈɡrænmʌðə(r)/',cn:'祖母',cat:'家庭'},
  {g:3,term:'上',u:6,w:'grandma',ipa:'/ˈɡrænmɑː/',cn:'奶奶',cat:'家庭'},
  {g:3,term:'上',u:6,w:'how',ipa:'/haʊ/',cn:'怎么',cat:'疑问'},
  {g:3,term:'上',u:6,w:'old',ipa:'/əʊld/',cn:'…岁的',cat:'形容词'},
  {g:3,term:'上',u:6,w:'year',ipa:'/jɪə(r)/',cn:'岁；年',cat:'其他'},
  {g:3,term:'上',u:6,w:'plate',ipa:'/pleɪt/',cn:'盘子',cat:'餐具'},
  {g:3,term:'上',u:6,w:'happy',ipa:'/ˈhæpi/',cn:'快乐的',cat:'形容词'},
  {g:3,term:'上',u:6,w:'birthday',ipa:'/ˈbɜːθdeɪ/',cn:'生日',cat:'其他'},
  {g:3,term:'下',u:1,w:'UK',ipa:'/ˌjuː ˈkeɪ/',cn:'英国',cat:'国家'},
  {g:3,term:'下',u:1,w:'Canada',ipa:'/ˈkænədə/',cn:'加拿大',cat:'国家'},
  {g:3,term:'下',u:1,w:'USA',ipa:'/ˌjuː es ˈeɪ/',cn:'美国',cat:'国家'},
  {g:3,term:'下',u:1,w:'China',ipa:'/ˈtʃaɪnə/',cn:'中国',cat:'国家'},
  {g:3,term:'下',u:1,w:'she',ipa:'/ʃiː/',cn:'她',cat:'代词'},
  {g:3,term:'下',u:1,w:'student',ipa:'/ˈstjuːdnt/',cn:'学生',cat:'人物'},
  {g:3,term:'下',u:1,w:'pupil',ipa:'/ˈpjuːpl/',cn:'小学生',cat:'人物'},
  {g:3,term:'下',u:1,w:'he',ipa:'/hiː/',cn:'他',cat:'代词'},
  {g:3,term:'下',u:1,w:'teacher',ipa:'/ˈtiːtʃə(r)/',cn:'教师',cat:'人物'},
  {g:3,term:'下',u:2,w:'father',ipa:'/ˈfɑːðə(r)/',cn:'父亲',cat:'家庭'},
  {g:3,term:'下',u:2,w:'mother',ipa:'/ˈmʌðə(r)/',cn:'母亲',cat:'家庭'},
  {g:3,term:'下',u:2,w:'man',ipa:'/mæn/',cn:'男人',cat:'人物'},
  {g:3,term:'下',u:2,w:'woman',ipa:'/ˈwʊmən/',cn:'女人',cat:'人物'},
  {g:3,term:'下',u:2,w:'grandmother',ipa:'/ˈɡrænmʌðə(r)/',cn:'（外）祖母',cat:'家庭'},
  {g:3,term:'下',u:2,w:'grandfather',ipa:'/ˈɡrænfɑːðə(r)/',cn:'（外）祖父',cat:'家庭'},
  {g:3,term:'下',u:2,w:'sister',ipa:'/ˈsɪstə(r)/',cn:'姐；妹',cat:'家庭'},
  {g:3,term:'下',u:2,w:'family',ipa:'/ˈfæməli/',cn:'家庭',cat:'家庭'},
  {g:3,term:'下',u:3,w:'thin',ipa:'/θɪn/',cn:'瘦的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'fat',ipa:'/fæt/',cn:'胖的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'tall',ipa:'/tɔːl/',cn:'高的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'short',ipa:'/ʃɔːt/',cn:'矮的；短的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'long',ipa:'/lɒŋ/',cn:'长的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'small',ipa:'/smɔːl/',cn:'小的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'big',ipa:'/bɪɡ/',cn:'大的',cat:'形容词'},
  {g:3,term:'下',u:3,w:'giraffe',ipa:'/dʒəˈrɑːf/',cn:'长颈鹿',cat:'动物'},
  {g:3,term:'下',u:4,w:'on',ipa:'/ɒn/',cn:'在……上',cat:'介词'},
  {g:3,term:'下',u:4,w:'in',ipa:'/ɪn/',cn:'在……里',cat:'介词'},
  {g:3,term:'下',u:4,w:'under',ipa:'/ˈʌndə(r)/',cn:'在……下面',cat:'介词'},
  {g:3,term:'下',u:4,w:'chair',ipa:'/tʃeə(r)/',cn:'椅子',cat:'家具'},
  {g:3,term:'下',u:4,w:'desk',ipa:'/desk/',cn:'书桌',cat:'家具'},
  {g:3,term:'下',u:4,w:'cap',ipa:'/kæp/',cn:'帽子',cat:'衣物'},
  {g:3,term:'下',u:4,w:'ball',ipa:'/bɔːl/',cn:'球',cat:'玩具'},
  {g:3,term:'下',u:4,w:'car',ipa:'/kɑː(r)/',cn:'小汽车',cat:'交通'},
  {g:3,term:'下',u:4,w:'boat',ipa:'/bəʊt/',cn:'小船',cat:'交通'},
  {g:3,term:'下',u:4,w:'map',ipa:'/mæp/',cn:'地图',cat:'其他'},
  {g:3,term:'下',u:4,w:'toy',ipa:'/tɔɪ/',cn:'玩具',cat:'玩具'},
  {g:3,term:'下',u:4,w:'box',ipa:'/bɒks/',cn:'盒；箱',cat:'其他'},
  {g:3,term:'下',u:5,w:'pear',ipa:'/peə(r)/',cn:'梨',cat:'水果'},
  {g:3,term:'下',u:5,w:'apple',ipa:'/ˈæpl/',cn:'苹果',cat:'水果'},
  {g:3,term:'下',u:5,w:'orange',ipa:'/ˈɒrɪndʒ/',cn:'橙子',cat:'水果'},
  {g:3,term:'下',u:5,w:'banana',ipa:'/bəˈnɑːnə/',cn:'香蕉',cat:'水果'},
  {g:3,term:'下',u:5,w:'watermelon',ipa:'/ˈwɔːtəmelən/',cn:'西瓜',cat:'水果'},
  {g:3,term:'下',u:5,w:'strawberry',ipa:'/ˈstrɔːbəri/',cn:'草莓',cat:'水果'},
  {g:3,term:'下',u:5,w:'grape',ipa:'/ɡreɪp/',cn:'葡萄',cat:'水果'},
  {g:3,term:'下',u:6,w:'eleven',ipa:'/ɪˈlevn/',cn:'十一',cat:'数字'},
  {g:3,term:'下',u:6,w:'twelve',ipa:'/twelv/',cn:'十二',cat:'数字'},
  {g:3,term:'下',u:6,w:'thirteen',ipa:'/ˌθɜːˈtiːn/',cn:'十三',cat:'数字'},
  {g:3,term:'下',u:6,w:'fourteen',ipa:'/ˌfɔːˈtiːn/',cn:'十四',cat:'数字'},
  {g:3,term:'下',u:6,w:'fifteen',ipa:'/ˌfɪfˈtiːn/',cn:'十五',cat:'数字'},
  {g:3,term:'下',u:6,w:'sixteen',ipa:'/ˌsɪksˈtiːn/',cn:'十六',cat:'数字'},
  {g:3,term:'下',u:6,w:'seventeen',ipa:'/ˌsevnˈtiːn/',cn:'十七',cat:'数字'},
  {g:3,term:'下',u:6,w:'eighteen',ipa:'/ˌeɪˈtiːn/',cn:'十八',cat:'数字'},
  {g:3,term:'下',u:6,w:'nineteen',ipa:'/ˌnaɪnˈtiːn/',cn:'十九',cat:'数字'},
  {g:3,term:'下',u:6,w:'twenty',ipa:'/ˈtwenti/',cn:'二十',cat:'数字'},
  {g:3,term:'下',u:6,w:'kite',ipa:'/kaɪt/',cn:'风筝',cat:'玩具'},
  {g:3,term:'下',u:1,w:'boy',ipa:'/bɔɪ/',cn:'男孩',cat:'人物'},
  {g:3,term:'下',u:1,w:'girl',ipa:'/ɡɜːl/',cn:'女孩',cat:'人物'},
  {g:3,term:'下',u:1,w:'friend',ipa:'/frend/',cn:'朋友',cat:'人物'},
  {g:3,term:'下',u:1,w:'new',ipa:'/njuː/',cn:'新的',cat:'形容词'},
  {g:3,term:'下',u:1,w:'today',ipa:'/təˈdeɪ/',cn:'今天',cat:'时间'},
  {g:3,term:'下',u:1,w:'and',ipa:'/ænd/',cn:'和；与',cat:'连词'},
  {g:3,term:'下',u:2,w:'brother',ipa:'/ˈbrʌðə(r)/',cn:'兄；弟',cat:'家庭'},
  {g:3,term:'下',u:2,w:'grandpa',ipa:'/ˈɡrænpɑː/',cn:'（外）祖父',cat:'家庭'},
  {g:3,term:'下',u:2,w:'grandma',ipa:'/ˈɡrænmɑː/',cn:'（外）祖母',cat:'家庭'},
  {g:3,term:'下',u:2,w:'dad',ipa:'/dæd/',cn:'爸爸',cat:'家庭'},
  {g:3,term:'下',u:2,w:'mum',ipa:'/mʌm/',cn:'妈妈',cat:'家庭'},
  {g:3,term:'下',u:3,w:'children',ipa:'/ˈtʃɪldrən/',cn:'儿童',cat:'人物'},
  {g:3,term:'下',u:3,w:'tail',ipa:'/teɪl/',cn:'尾巴',cat:'动物'},
  {g:3,term:'下',u:3,w:'deer',ipa:'/dɪə(r)/',cn:'鹿',cat:'动物'},
  {g:3,term:'下',u:5,w:'buy',ipa:'/baɪ/',cn:'买',cat:'动词'},
  {g:3,term:'下',u:5,w:'fruit',ipa:'/fruːt/',cn:'水果',cat:'食物'},
  {g:3,term:'下',u:6,w:'beautiful',ipa:'/ˈbjuːtɪfl/',cn:'美丽的',cat:'形容词'},
  {g:4,term:'上',u:1,w:'classroom',ipa:'/ˈklɑːsruːm/',cn:'教室',cat:'场所'},
  {g:4,term:'上',u:1,w:'window',ipa:'/ˈwɪndəʊ/',cn:'窗户',cat:'教室'},
  {g:4,term:'上',u:1,w:'blackboard',ipa:'/ˈblækbɔːd/',cn:'黑板',cat:'教室'},
  {g:4,term:'上',u:1,w:'light',ipa:'/laɪt/',cn:'电灯',cat:'教室'},
  {g:4,term:'上',u:1,w:'picture',ipa:'/ˈpɪktʃə(r)/',cn:'图画',cat:'教室'},
  {g:4,term:'上',u:1,w:'door',ipa:'/dɔː(r)/',cn:'门',cat:'教室'},
  {g:4,term:'上',u:1,w:'teacher’s desk',ipa:'/ˈtiːtʃəz desk/',cn:'讲台',cat:'教室'},
  {g:4,term:'上',u:1,w:'computer',ipa:'/kəmˈpjuːtə(r)/',cn:'计算机',cat:'电器'},
  {g:4,term:'上',u:1,w:'fan',ipa:'/fæn/',cn:'风扇',cat:'电器'},
  {g:4,term:'上',u:1,w:'wall',ipa:'/wɔːl/',cn:'墙壁',cat:'教室'},
  {g:4,term:'上',u:1,w:'floor',ipa:'/flɔː(r)/',cn:'地板',cat:'教室'},
  {g:4,term:'上',u:2,w:'maths book',ipa:'/mæθs bʊk/',cn:'数学书',cat:'书籍'},
  {g:4,term:'上',u:2,w:'English book',ipa:'/ˈɪŋɡlɪʃ bʊk/',cn:'英语书',cat:'书籍'},
  {g:4,term:'上',u:2,w:'Chinese book',ipa:'/ˌtʃaɪˈniːz bʊk/',cn:'语文书',cat:'书籍'},
  {g:4,term:'上',u:2,w:'storybook',ipa:'/ˈstɔːribʊk/',cn:'故事书',cat:'书籍'},
  {g:4,term:'上',u:2,w:'candy',ipa:'/ˈkændi/',cn:'糖果',cat:'食物'},
  {g:4,term:'上',u:2,w:'notebook',ipa:'/ˈnəʊtbʊk/',cn:'笔记本',cat:'文具'},
  {g:4,term:'上',u:2,w:'toy',ipa:'/tɔɪ/',cn:'玩具',cat:'玩具'},
  {g:4,term:'上',u:2,w:'key',ipa:'/kiː/',cn:'钥匙',cat:'其他'},
  {g:4,term:'上',u:2,w:'schoolbag',ipa:'/ˈskuːlbæɡ/',cn:'书包',cat:'文具'},
  {g:4,term:'上',u:3,w:'strong',ipa:'/strɒŋ/',cn:'强壮的',cat:'形容词'},
  {g:4,term:'上',u:3,w:'friendly',ipa:'/ˈfrendli/',cn:'友好的',cat:'形容词'},
  {g:4,term:'上',u:3,w:'quiet',ipa:'/ˈkwaɪət/',cn:'安静的',cat:'形容词'},
  {g:4,term:'上',u:3,w:'hair',ipa:'/heə(r)/',cn:'头发',cat:'身体'},
  {g:4,term:'上',u:3,w:'shoe',ipa:'/ʃuː/',cn:'鞋',cat:'衣物'},
  {g:4,term:'上',u:3,w:'glasses',ipa:'/ˈɡlɑːsɪz/',cn:'眼镜',cat:'衣物'},
  {g:4,term:'上',u:4,w:'bedroom',ipa:'/ˈbedruːm/',cn:'卧室',cat:'房间'},
  {g:4,term:'上',u:4,w:'living room',ipa:'/ˈlɪvɪŋ ruːm/',cn:'客厅',cat:'房间'},
  {g:4,term:'上',u:4,w:'study',ipa:'/ˈstʌdi/',cn:'书房',cat:'房间'},
  {g:4,term:'上',u:4,w:'kitchen',ipa:'/ˈkɪtʃɪn/',cn:'厨房',cat:'房间'},
  {g:4,term:'上',u:4,w:'bathroom',ipa:'/ˈbɑːθruːm/',cn:'浴室',cat:'房间'},
  {g:4,term:'上',u:4,w:'bed',ipa:'/bed/',cn:'床',cat:'家具'},
  {g:4,term:'上',u:4,w:'phone',ipa:'/fəʊn/',cn:'电话',cat:'电器'},
  {g:4,term:'上',u:4,w:'table',ipa:'/ˈteɪbl/',cn:'桌子',cat:'家具'},
  {g:4,term:'上',u:4,w:'sofa',ipa:'/ˈsəʊfə/',cn:'沙发',cat:'家具'},
  {g:4,term:'上',u:4,w:'fridge',ipa:'/frɪdʒ/',cn:'冰箱',cat:'电器'},
  {g:4,term:'上',u:5,w:'beef',ipa:'/biːf/',cn:'牛肉',cat:'食物'},
  {g:4,term:'上',u:5,w:'chicken',ipa:'/ˈtʃɪkɪn/',cn:'鸡肉',cat:'食物'},
  {g:4,term:'上',u:5,w:'noodles',ipa:'/ˈnuːdlz/',cn:'面条',cat:'食物'},
  {g:4,term:'上',u:5,w:'soup',ipa:'/suːp/',cn:'汤',cat:'食物'},
  {g:4,term:'上',u:5,w:'vegetable',ipa:'/ˈvedʒtəbl/',cn:'蔬菜',cat:'食物'},
  {g:4,term:'上',u:5,w:'chopsticks',ipa:'/ˈtʃɒpstɪks/',cn:'筷子',cat:'餐具'},
  {g:4,term:'上',u:5,w:'bowl',ipa:'/bəʊl/',cn:'碗',cat:'餐具'},
  {g:4,term:'上',u:5,w:'fork',ipa:'/fɔːk/',cn:'餐叉',cat:'餐具'},
  {g:4,term:'上',u:5,w:'knife',ipa:'/naɪf/',cn:'刀',cat:'餐具'},
  {g:4,term:'上',u:5,w:'spoon',ipa:'/spuːn/',cn:'勺',cat:'餐具'},
  {g:4,term:'上',u:6,w:'parents',ipa:'/ˈpeərənts/',cn:'父母',cat:'家庭'},
  {g:4,term:'上',u:6,w:'cousin',ipa:'/ˈkʌzn/',cn:'堂（表）兄弟（姐妹）',cat:'家庭'},
  {g:4,term:'上',u:6,w:'uncle',ipa:'/ˈʌŋkl/',cn:'舅父；叔父',cat:'家庭'},
  {g:4,term:'上',u:6,w:'aunt',ipa:'/ɑːnt/',cn:'姑母；姨母',cat:'家庭'},
  {g:4,term:'上',u:6,w:'baby brother',ipa:'/ˈbeɪbi ˈbrʌðə(r)/',cn:'婴儿小弟弟',cat:'家庭'},
  {g:4,term:'上',u:6,w:'doctor',ipa:'/ˈdɒktə(r)/',cn:'医生',cat:'职业'},
  {g:4,term:'上',u:6,w:'cook',ipa:'/kʊk/',cn:'厨师',cat:'职业'},
  {g:4,term:'上',u:6,w:'driver',ipa:'/ˈdraɪvə(r)/',cn:'司机',cat:'职业'},
  {g:4,term:'上',u:6,w:'farmer',ipa:'/ˈfɑːmə(r)/',cn:'农民',cat:'职业'},
  {g:4,term:'上',u:6,w:'nurse',ipa:'/nɜːs/',cn:'护士',cat:'职业'},
  {g:4,term:'上',u:2,w:'cute',ipa:'/kjuːt/',cn:'可爱的',cat:'形容词'},
  {g:4,term:'上',u:3,w:'his',ipa:'/hɪz/',cn:'他的',cat:'代词'},
  {g:4,term:'上',u:3,w:'her',ipa:'/hɜː(r)/',cn:'她的',cat:'代词'},
  {g:4,term:'上',u:3,w:'right',ipa:'/raɪt/',cn:'正确的；右边',cat:'形容词'},
  {g:4,term:'上',u:3,w:'or',ipa:'/ɔː(r)/',cn:'或者；还是',cat:'连词'},
  {g:4,term:'上',u:3,w:'hat',ipa:'/hæt/',cn:'帽子',cat:'衣物'},
  {g:4,term:'上',u:6,w:'baby',ipa:'/ˈbeɪbi/',cn:'婴儿',cat:'人物'},
  {g:4,term:'下',u:1,w:'first floor',ipa:'/fɜːst flɔː(r)/',cn:'一楼',cat:'场所'},
  {g:4,term:'下',u:1,w:'second floor',ipa:'/ˈsekənd flɔː(r)/',cn:'二楼',cat:'场所'},
  {g:4,term:'下',u:1,w:'teachers’ office',ipa:'/ˈtiːtʃəz ˈɒfɪs/',cn:'教师办公室',cat:'场所'},
  {g:4,term:'下',u:1,w:'library',ipa:'/ˈlaɪbrəri/',cn:'图书馆',cat:'场所'},
  {g:4,term:'下',u:1,w:'playground',ipa:'/ˈpleɪɡraʊnd/',cn:'操场',cat:'场所'},
  {g:4,term:'下',u:1,w:'computer room',ipa:'/kəmˈpjuːtə ruːm/',cn:'计算机房',cat:'场所'},
  {g:4,term:'下',u:1,w:'art room',ipa:'/ɑːt ruːm/',cn:'美术教室',cat:'场所'},
  {g:4,term:'下',u:1,w:'music room',ipa:'/ˈmjuːzɪk ruːm/',cn:'音乐教室',cat:'场所'},
  {g:4,term:'下',u:1,w:'gym',ipa:'/dʒɪm/',cn:'体育馆',cat:'场所'},
  {g:4,term:'下',u:2,w:'breakfast',ipa:'/ˈbrekfəst/',cn:'早餐',cat:'餐饮'},
  {g:4,term:'下',u:2,w:'English class',ipa:'/ˈɪŋɡlɪʃ klɑːs/',cn:'英语课',cat:'课程'},
  {g:4,term:'下',u:2,w:'lunch',ipa:'/lʌntʃ/',cn:'午餐',cat:'餐饮'},
  {g:4,term:'下',u:2,w:'music class',ipa:'/ˈmjuːzɪk klɑːs/',cn:'音乐课',cat:'课程'},
  {g:4,term:'下',u:2,w:'PE class',ipa:'/ˌpiː ˈiː klɑːs/',cn:'体育课',cat:'课程'},
  {g:4,term:'下',u:2,w:'dinner',ipa:'/ˈdɪnə(r)/',cn:'晚餐',cat:'餐饮'},
  {g:4,term:'下',u:2,w:'get up',ipa:'/ɡet ʌp/',cn:'起床',cat:'动词'},
  {g:4,term:'下',u:2,w:'go to school',ipa:'/ɡəʊ tə skuːl/',cn:'去上学',cat:'动词'},
  {g:4,term:'下',u:2,w:'go home',ipa:'/ɡəʊ həʊm/',cn:'回家',cat:'动词'},
  {g:4,term:'下',u:2,w:'go to bed',ipa:'/ɡəʊ tə bed/',cn:'上床睡觉',cat:'动词'},
  {g:4,term:'下',u:3,w:'cold',ipa:'/kəʊld/',cn:'寒冷的',cat:'天气'},
  {g:4,term:'下',u:3,w:'cool',ipa:'/kuːl/',cn:'凉爽的',cat:'天气'},
  {g:4,term:'下',u:3,w:'warm',ipa:'/wɔːm/',cn:'温暖的',cat:'天气'},
  {g:4,term:'下',u:3,w:'hot',ipa:'/hɒt/',cn:'热的',cat:'天气'},
  {g:4,term:'下',u:3,w:'sunny',ipa:'/ˈsʌni/',cn:'阳光充足的',cat:'天气'},
  {g:4,term:'下',u:3,w:'windy',ipa:'/ˈwɪndi/',cn:'多风的',cat:'天气'},
  {g:4,term:'下',u:3,w:'cloudy',ipa:'/ˈklaʊdi/',cn:'多云的',cat:'天气'},
  {g:4,term:'下',u:3,w:'snowy',ipa:'/ˈsnəʊi/',cn:'下雪的',cat:'天气'},
  {g:4,term:'下',u:3,w:'rainy',ipa:'/ˈreɪni/',cn:'下雨的',cat:'天气'},
  {g:4,term:'下',u:4,w:'tomato',ipa:'/təˈmɑːtəʊ/',cn:'西红柿',cat:'蔬菜'},
  {g:4,term:'下',u:4,w:'potato',ipa:'/pəˈteɪtəʊ/',cn:'土豆',cat:'蔬菜'},
  {g:4,term:'下',u:4,w:'green beans',ipa:'/ɡriːn biːnz/',cn:'豆角',cat:'蔬菜'},
  {g:4,term:'下',u:4,w:'carrot',ipa:'/ˈkærət/',cn:'胡萝卜',cat:'蔬菜'},
  {g:4,term:'下',u:4,w:'horse',ipa:'/hɔːs/',cn:'马',cat:'动物'},
  {g:4,term:'下',u:4,w:'cow',ipa:'/kaʊ/',cn:'母牛',cat:'动物'},
  {g:4,term:'下',u:4,w:'sheep',ipa:'/ʃiːp/',cn:'羊',cat:'动物'},
  {g:4,term:'下',u:4,w:'hen',ipa:'/hen/',cn:'母鸡',cat:'动物'},
  {g:4,term:'下',u:5,w:'clothes',ipa:'/kləʊðz/',cn:'衣服',cat:'衣物'},
  {g:4,term:'下',u:5,w:'pants',ipa:'/pænts/',cn:'裤子',cat:'衣物'},
  {g:4,term:'下',u:5,w:'hat',ipa:'/hæt/',cn:'帽子',cat:'衣物'},
  {g:4,term:'下',u:5,w:'dress',ipa:'/dres/',cn:'连衣裙',cat:'衣物'},
  {g:4,term:'下',u:5,w:'skirt',ipa:'/skɜːt/',cn:'女裙',cat:'衣物'},
  {g:4,term:'下',u:5,w:'coat',ipa:'/kəʊt/',cn:'外衣',cat:'衣物'},
  {g:4,term:'下',u:5,w:'sweater',ipa:'/ˈswetə(r)/',cn:'毛衣',cat:'衣物'},
  {g:4,term:'下',u:5,w:'sock',ipa:'/sɒk/',cn:'短袜',cat:'衣物'},
  {g:4,term:'下',u:5,w:'shorts',ipa:'/ʃɔːts/',cn:'短裤',cat:'衣物'},
  {g:4,term:'下',u:5,w:'jacket',ipa:'/ˈdʒækɪt/',cn:'夹克衫',cat:'衣物'},
  {g:4,term:'下',u:6,w:'glove',ipa:'/ɡlʌv/',cn:'手套',cat:'衣物'},
  {g:4,term:'下',u:6,w:'scarf',ipa:'/skɑːf/',cn:'围巾',cat:'衣物'},
  {g:4,term:'下',u:6,w:'umbrella',ipa:'/ʌmˈbrelə/',cn:'雨伞',cat:'其他'},
  {g:4,term:'下',u:6,w:'sunglasses',ipa:'/ˈsʌnɡlɑːsɪz/',cn:'太阳镜',cat:'衣物'},
  {g:4,term:'下',u:6,w:'pretty',ipa:'/ˈprɪti/',cn:'美观的',cat:'形容词'},
  {g:4,term:'下',u:6,w:'expensive',ipa:'/ɪkˈspensɪv/',cn:'昂贵的',cat:'形容词'},
  {g:4,term:'下',u:6,w:'cheap',ipa:'/tʃiːp/',cn:'便宜的',cat:'形容词'},
  {g:4,term:'下',u:6,w:'nice',ipa:'/naɪs/',cn:'好的',cat:'形容词'},
  {g:4,term:'下',u:1,w:'next to',ipa:'/nekst tuː/',cn:'紧邻；在……近旁',cat:'介词'},
  {g:4,term:'下',u:1,w:'homework',ipa:'/ˈhəʊmwɜːk/',cn:'作业',cat:'其他'},
  {g:4,term:'下',u:1,w:'class',ipa:'/klɑːs/',cn:'班级；课',cat:'其他'},
  {g:4,term:'下',u:1,w:'forty',ipa:'/ˈfɔːti/',cn:'四十',cat:'数字'},
  {g:4,term:'下',u:1,w:'way',ipa:'/weɪ/',cn:'方向；路',cat:'其他'},
  {g:4,term:'下',u:2,w:'o’clock',ipa:'/əˈklɒk/',cn:'……点钟',cat:'其他'},
  {g:4,term:'下',u:3,w:'outside',ipa:'/ˌaʊtˈsaɪd/',cn:'在户外',cat:'副词'},
  {g:4,term:'下',u:3,w:'weather',ipa:'/ˈweðə(r)/',cn:'天气',cat:'其他'},
  {g:4,term:'下',u:4,w:'these',ipa:'/ðiːz/',cn:'这些',cat:'代词'},
  {g:4,term:'下',u:4,w:'those',ipa:'/ðəʊz/',cn:'那些',cat:'代词'},
  {g:4,term:'下',u:4,w:'animal',ipa:'/ˈænɪml/',cn:'动物',cat:'动物'},
  {g:4,term:'下',u:5,w:'shirt',ipa:'/ʃɜːt/',cn:'衬衫',cat:'衣物'},
  {g:4,term:'下',u:5,w:'yours',ipa:'/jɔːz/',cn:'你（们）的',cat:'代词'},
  {g:4,term:'下',u:5,w:'whose',ipa:'/huːz/',cn:'谁的',cat:'代词'},
  {g:4,term:'下',u:6,w:'try on',ipa:'/traɪ ɒn/',cn:'试穿',cat:'动词'},
  {g:4,term:'下',u:6,w:'size',ipa:'/saɪz/',cn:'尺码',cat:'其他'},
  {g:4,term:'下',u:6,w:'eighty',ipa:'/ˈeɪti/',cn:'八十',cat:'数字'},
  {g:4,term:'下',u:6,w:'dollar',ipa:'/ˈdɒlə(r)/',cn:'美元',cat:'其他'},
  {g:5,term:'上',u:1,w:'old',ipa:'/əʊld/',cn:'老的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'young',ipa:'/jʌŋ/',cn:'年轻的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'funny',ipa:'/ˈfʌni/',cn:'滑稽的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'kind',ipa:'/kaɪnd/',cn:'和蔼的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'strict',ipa:'/strɪkt/',cn:'严格的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'polite',ipa:'/pəˈlaɪt/',cn:'有礼貌的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'hard-working',ipa:'/ˌhɑːd ˈwɜːkɪŋ/',cn:'勤奋的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'helpful',ipa:'/ˈhelpfl/',cn:'有用的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'clever',ipa:'/ˈklevə(r)/',cn:'聪明的',cat:'形容词'},
  {g:5,term:'上',u:1,w:'shy',ipa:'/ʃaɪ/',cn:'羞怯的',cat:'形容词'},
  {g:5,term:'上',u:2,w:'Monday',ipa:'/ˈmʌndeɪ/',cn:'星期一',cat:'星期'},
  {g:5,term:'上',u:2,w:'Tuesday',ipa:'/ˈtjuːzdeɪ/',cn:'星期二',cat:'星期'},
  {g:5,term:'上',u:2,w:'Wednesday',ipa:'/ˈwenzdeɪ/',cn:'星期三',cat:'星期'},
  {g:5,term:'上',u:2,w:'Thursday',ipa:'/ˈθɜːzdeɪ/',cn:'星期四',cat:'星期'},
  {g:5,term:'上',u:2,w:'Friday',ipa:'/ˈfraɪdeɪ/',cn:'星期五',cat:'星期'},
  {g:5,term:'上',u:2,w:'Saturday',ipa:'/ˈsætədeɪ/',cn:'星期六',cat:'星期'},
  {g:5,term:'上',u:2,w:'Sunday',ipa:'/ˈsʌndeɪ/',cn:'星期日',cat:'星期'},
  {g:5,term:'上',u:2,w:'weekend',ipa:'/ˌwiːkˈend/',cn:'周末',cat:'时间'},
  {g:5,term:'上',u:3,w:'salad',ipa:'/ˈsæləd/',cn:'沙拉',cat:'食物'},
  {g:5,term:'上',u:3,w:'hamburger',ipa:'/ˈhæmbɜːɡə(r)/',cn:'汉堡包',cat:'食物'},
  {g:5,term:'上',u:3,w:'ice cream',ipa:'/aɪs kriːm/',cn:'冰激凌',cat:'食物'},
  {g:5,term:'上',u:3,w:'tea',ipa:'/tiː/',cn:'茶',cat:'食物'},
  {g:5,term:'上',u:3,w:'sandwich',ipa:'/ˈsænwɪtʃ/',cn:'三明治',cat:'食物'},
  {g:5,term:'上',u:3,w:'fresh',ipa:'/freʃ/',cn:'新鲜的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'healthy',ipa:'/ˈhelθi/',cn:'健康的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'delicious',ipa:'/dɪˈlɪʃəs/',cn:'美味的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'hot',ipa:'/hɒt/',cn:'辣的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'sweet',ipa:'/swiːt/',cn:'甜的',cat:'形容词'},
  {g:5,term:'上',u:4,w:'sing',ipa:'/sɪŋ/',cn:'唱',cat:'动词'},
  {g:5,term:'上',u:4,w:'song',ipa:'/sɒŋ/',cn:'歌曲',cat:'其他'},
  {g:5,term:'上',u:4,w:'dance',ipa:'/dɑːns/',cn:'跳舞',cat:'动词'},
  {g:5,term:'上',u:4,w:'draw',ipa:'/drɔː/',cn:'画',cat:'动词'},
  {g:5,term:'上',u:4,w:'cartoon',ipa:'/kɑːˈtuːn/',cn:'漫画',cat:'其他'},
  {g:5,term:'上',u:4,w:'cook',ipa:'/kʊk/',cn:'烹调',cat:'动词'},
  {g:5,term:'上',u:4,w:'swim',ipa:'/swɪm/',cn:'游泳',cat:'动词'},
  {g:5,term:'上',u:4,w:'ping-pong',ipa:'/ˈpɪŋ pɒŋ/',cn:'乒乓球',cat:'运动'},
  {g:5,term:'上',u:4,w:'kung fu',ipa:'/ˌkʌŋ ˈfuː/',cn:'武术',cat:'运动'},
  {g:5,term:'上',u:4,w:'speak',ipa:'/spiːk/',cn:'说',cat:'动词'},
  {g:5,term:'上',u:4,w:'play',ipa:'/pleɪ/',cn:'玩',cat:'动词'},
  {g:5,term:'上',u:5,w:'clock',ipa:'/klɒk/',cn:'时钟',cat:'家具'},
  {g:5,term:'上',u:5,w:'plant',ipa:'/plɑːnt/',cn:'植物',cat:'其他'},
  {g:5,term:'上',u:5,w:'bottle',ipa:'/ˈbɒtl/',cn:'瓶子',cat:'其他'},
  {g:5,term:'上',u:5,w:'bike',ipa:'/baɪk/',cn:'自行车',cat:'交通'},
  {g:5,term:'上',u:5,w:'photo',ipa:'/ˈfəʊtəʊ/',cn:'照片',cat:'其他'},
  {g:5,term:'上',u:5,w:'front',ipa:'/frʌnt/',cn:'正面',cat:'方位'},
  {g:5,term:'上',u:5,w:'between',ipa:'/bɪˈtwiːn/',cn:'在……中间',cat:'介词'},
  {g:5,term:'上',u:5,w:'above',ipa:'/əˈbʌv/',cn:'在……上面',cat:'介词'},
  {g:5,term:'上',u:5,w:'beside',ipa:'/bɪˈsaɪd/',cn:'在……旁边',cat:'介词'},
  {g:5,term:'上',u:5,w:'behind',ipa:'/bɪˈhaɪnd/',cn:'在……后面',cat:'介词'},
  {g:5,term:'上',u:6,w:'forest',ipa:'/ˈfɒrɪst/',cn:'森林',cat:'自然'},
  {g:5,term:'上',u:6,w:'river',ipa:'/ˈrɪvə(r)/',cn:'河',cat:'自然'},
  {g:5,term:'上',u:6,w:'lake',ipa:'/leɪk/',cn:'湖',cat:'自然'},
  {g:5,term:'上',u:6,w:'mountain',ipa:'/ˈmaʊntən/',cn:'高山',cat:'自然'},
  {g:5,term:'上',u:6,w:'hill',ipa:'/hɪl/',cn:'山丘',cat:'自然'},
  {g:5,term:'上',u:6,w:'tree',ipa:'/triː/',cn:'树',cat:'自然'},
  {g:5,term:'上',u:6,w:'bridge',ipa:'/brɪdʒ/',cn:'桥',cat:'自然'},
  {g:5,term:'上',u:6,w:'building',ipa:'/ˈbɪldɪŋ/',cn:'建筑物',cat:'自然'},
  {g:5,term:'上',u:6,w:'village',ipa:'/ˈvɪlɪdʒ/',cn:'村庄',cat:'场所'},
  {g:5,term:'上',u:6,w:'house',ipa:'/haʊs/',cn:'房子',cat:'房间'},
  {g:5,term:'上',u:2,w:'wash',ipa:'/wɒʃ/',cn:'洗',cat:'动词'},
  {g:5,term:'上',u:2,w:'watch',ipa:'/wɒtʃ/',cn:'看；观看',cat:'动词'},
  {g:5,term:'上',u:2,w:'read',ipa:'/riːd/',cn:'读；阅读',cat:'动词'},
  {g:5,term:'上',u:2,w:'often',ipa:'/ˈɒfn/',cn:'经常',cat:'副词'},
  {g:5,term:'上',u:2,w:'park',ipa:'/pɑːk/',cn:'公园',cat:'场所'},
  {g:5,term:'上',u:2,w:'tired',ipa:'/ˈtaɪəd/',cn:'疲倦的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'drink',ipa:'/drɪŋk/',cn:'喝',cat:'动词'},
  {g:5,term:'上',u:3,w:'thirsty',ipa:'/ˈθɜːsti/',cn:'口渴的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'favourite',ipa:'/ˈfeɪvərɪt/',cn:'特别喜爱的',cat:'形容词'},
  {g:5,term:'上',u:3,w:'food',ipa:'/fuːd/',cn:'食物',cat:'食物'},
  {g:5,term:'上',u:3,w:'onion',ipa:'/ˈʌnjən/',cn:'洋葱',cat:'蔬菜'},
  {g:5,term:'上',u:4,w:'we',ipa:'/wiː/',cn:'我们',cat:'代词'},
  {g:5,term:'上',u:4,w:'robot',ipa:'/ˈrəʊbɒt/',cn:'机器人',cat:'其他'},
  {g:5,term:'上',u:4,w:'him',ipa:'/hɪm/',cn:'他（宾格）',cat:'代词'},
  {g:5,term:'上',u:4,w:'want',ipa:'/wɒnt/',cn:'想要',cat:'动词'},
  {g:5,term:'上',u:4,w:'send',ipa:'/send/',cn:'发送',cat:'动词'},
  {g:5,term:'上',u:4,w:'email',ipa:'/ˈiːmeɪl/',cn:'电子邮件',cat:'其他'},
  {g:5,term:'上',u:5,w:'grandparent',ipa:'/ˈɡrænpeərənt/',cn:'祖父（母）',cat:'家庭'},
  {g:5,term:'上',u:5,w:'their',ipa:'/ðeə(r)/',cn:'他们的',cat:'代词'},
  {g:5,term:'上',u:5,w:'flower',ipa:'/ˈflaʊə(r)/',cn:'花',cat:'植物'},
  {g:5,term:'上',u:5,w:'live',ipa:'/lɪv/',cn:'居住',cat:'动词'},
  {g:5,term:'上',u:5,w:'nature',ipa:'/ˈneɪtʃə(r)/',cn:'自然',cat:'自然'},
  {g:5,term:'上',u:6,w:'boating',ipa:'/ˈbəʊtɪŋ/',cn:'划船',cat:'运动'},
  {g:5,term:'上',u:6,w:'rabbit',ipa:'/ˈræbɪt/',cn:'兔子',cat:'动物'},
  {g:5,term:'上',u:6,w:'high',ipa:'/haɪ/',cn:'高的',cat:'形容词'},
  {g:5,term:'下',u:1,w:'eat breakfast',ipa:'/iːt ˈbrekfəst/',cn:'吃早饭',cat:'动词'},
  {g:5,term:'下',u:1,w:'have…class',ipa:'/hæv klɑːs/',cn:'上……课',cat:'动词'},
  {g:5,term:'下',u:1,w:'play sports',ipa:'/pleɪ spɔːts/',cn:'进行体育活动',cat:'动词'},
  {g:5,term:'下',u:1,w:'do morning exercises',ipa:'/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/',cn:'做早操',cat:'动词'},
  {g:5,term:'下',u:1,w:'eat dinner',ipa:'/iːt ˈdɪnə(r)/',cn:'吃晚饭',cat:'动词'},
  {g:5,term:'下',u:1,w:'clean my room',ipa:'/kliːn maɪ ruːm/',cn:'打扫我的房间',cat:'动词'},
  {g:5,term:'下',u:1,w:'go for a walk',ipa:'/ɡəʊ fər ə wɔːk/',cn:'散步',cat:'动词'},
  {g:5,term:'下',u:1,w:'go shopping',ipa:'/ɡəʊ ˈʃɒpɪŋ/',cn:'去买东西',cat:'动词'},
  {g:5,term:'下',u:1,w:'take a dancing class',ipa:'/teɪk ə ˈdɑːnsɪŋ klɑːs/',cn:'上舞蹈课',cat:'动词'},
  {g:5,term:'下',u:2,w:'spring',ipa:'/sprɪŋ/',cn:'春天',cat:'季节'},
  {g:5,term:'下',u:2,w:'summer',ipa:'/ˈsʌmə(r)/',cn:'夏天',cat:'季节'},
  {g:5,term:'下',u:2,w:'autumn',ipa:'/ˈɔːtəm/',cn:'秋天',cat:'季节'},
  {g:5,term:'下',u:2,w:'winter',ipa:'/ˈwɪntə(r)/',cn:'冬天',cat:'季节'},
  {g:5,term:'下',u:2,w:'season',ipa:'/ˈsiːzn/',cn:'季节',cat:'季节'},
  {g:5,term:'下',u:2,w:'picnic',ipa:'/ˈpɪknɪk/',cn:'野餐',cat:'其他'},
  {g:5,term:'下',u:2,w:'snowman',ipa:'/ˈsnəʊmæn/',cn:'雪人',cat:'其他'},
  {g:5,term:'下',u:2,w:'because',ipa:'/bɪˈkɒz/',cn:'因为',cat:'连词'},
  {g:5,term:'下',u:3,w:'January',ipa:'/ˈdʒænjuəri/',cn:'一月',cat:'月份'},
  {g:5,term:'下',u:3,w:'February',ipa:'/ˈfebruəri/',cn:'二月',cat:'月份'},
  {g:5,term:'下',u:3,w:'March',ipa:'/mɑːtʃ/',cn:'三月',cat:'月份'},
  {g:5,term:'下',u:3,w:'April',ipa:'/ˈeɪprəl/',cn:'四月',cat:'月份'},
  {g:5,term:'下',u:3,w:'May',ipa:'/meɪ/',cn:'五月',cat:'月份'},
  {g:5,term:'下',u:3,w:'June',ipa:'/dʒuːn/',cn:'六月',cat:'月份'},
  {g:5,term:'下',u:3,w:'July',ipa:'/dʒuˈlaɪ/',cn:'七月',cat:'月份'},
  {g:5,term:'下',u:3,w:'August',ipa:'/ˈɔːɡəst/',cn:'八月',cat:'月份'},
  {g:5,term:'下',u:3,w:'September',ipa:'/sepˈtembə(r)/',cn:'九月',cat:'月份'},
  {g:5,term:'下',u:3,w:'October',ipa:'/ɒkˈtəʊbə(r)/',cn:'十月',cat:'月份'},
  {g:5,term:'下',u:3,w:'November',ipa:'/nəʊˈvembə(r)/',cn:'十一月',cat:'月份'},
  {g:5,term:'下',u:3,w:'December',ipa:'/dɪˈsembə(r)/',cn:'十二月',cat:'月份'},
  {g:5,term:'下',u:4,w:'first',ipa:'/fɜːst/',cn:'第一',cat:'序数'},
  {g:5,term:'下',u:4,w:'second',ipa:'/ˈsekənd/',cn:'第二',cat:'序数'},
  {g:5,term:'下',u:4,w:'third',ipa:'/θɜːd/',cn:'第三',cat:'序数'},
  {g:5,term:'下',u:4,w:'fourth',ipa:'/fɔːθ/',cn:'第四',cat:'序数'},
  {g:5,term:'下',u:4,w:'fifth',ipa:'/fɪfθ/',cn:'第五',cat:'序数'},
  {g:5,term:'下',u:4,w:'twelfth',ipa:'/twelfθ/',cn:'第十二',cat:'序数'},
  {g:5,term:'下',u:4,w:'twentieth',ipa:'/ˈtwentiəθ/',cn:'第二十',cat:'序数'},
  {g:5,term:'下',u:4,w:'twenty-first',ipa:'/ˌtwenti ˈfɜːst/',cn:'第二十一',cat:'序数'},
  {g:5,term:'下',u:4,w:'twenty-third',ipa:'/ˌtwenti ˈθɜːd/',cn:'第二十三',cat:'序数'},
  {g:5,term:'下',u:4,w:'special',ipa:'/ˈspeʃl/',cn:'特殊的',cat:'形容词'},
  {g:5,term:'下',u:4,w:'festival',ipa:'/ˈfestɪvl/',cn:'节日',cat:'其他'},
  {g:5,term:'下',u:5,w:'mine',ipa:'/maɪn/',cn:'我的',cat:'代词'},
  {g:5,term:'下',u:5,w:'yours',ipa:'/jɔːz/',cn:'你（们）的',cat:'代词'},
  {g:5,term:'下',u:5,w:'his',ipa:'/hɪz/',cn:'他的',cat:'代词'},
  {g:5,term:'下',u:5,w:'hers',ipa:'/hɜːz/',cn:'她的',cat:'代词'},
  {g:5,term:'下',u:5,w:'theirs',ipa:'/ðeəz/',cn:'他们的',cat:'代词'},
  {g:5,term:'下',u:5,w:'ours',ipa:'/ˈaʊəz/',cn:'我们的',cat:'代词'},
  {g:5,term:'下',u:5,w:'climbing',ipa:'/ˈklaɪmɪŋ/',cn:'攀登',cat:'动词'},
  {g:5,term:'下',u:5,w:'eating',ipa:'/ˈiːtɪŋ/',cn:'吃',cat:'动词'},
  {g:5,term:'下',u:5,w:'playing',ipa:'/ˈpleɪɪŋ/',cn:'玩',cat:'动词'},
  {g:5,term:'下',u:5,w:'jumping',ipa:'/ˈdʒʌmpɪŋ/',cn:'跳',cat:'动词'},
  {g:5,term:'下',u:5,w:'drinking',ipa:'/ˈdrɪŋkɪŋ/',cn:'喝',cat:'动词'},
  {g:5,term:'下',u:5,w:'sleeping',ipa:'/ˈsliːpɪŋ/',cn:'睡觉',cat:'动词'},
  {g:5,term:'下',u:6,w:'doing morning exercises',ipa:'/ˈduːɪŋ ˈmɔːnɪŋ ˈeksəsaɪzɪz/',cn:'做早操',cat:'动词'},
  {g:5,term:'下',u:6,w:'having…class',ipa:'/ˈhævɪŋ klɑːs/',cn:'正在上……课',cat:'动词'},
  {g:5,term:'下',u:6,w:'eating lunch',ipa:'/ˈiːtɪŋ lʌntʃ/',cn:'吃午饭',cat:'动词'},
  {g:5,term:'下',u:6,w:'reading a book',ipa:'/ˈriːdɪŋ ə bʊk/',cn:'看书',cat:'动词'},
  {g:5,term:'下',u:6,w:'listening to music',ipa:'/ˈlɪsnɪŋ tə ˈmjuːzɪk/',cn:'听音乐',cat:'动词'},
  {g:5,term:'下',u:6,w:'keep',ipa:'/kiːp/',cn:'保持',cat:'动词'},
  {g:5,term:'下',u:6,w:'turn',ipa:'/tɜːn/',cn:'轮流',cat:'动词'},
  {g:5,term:'下',u:6,w:'talk quietly',ipa:'/tɔːk ˈkwaɪətli/',cn:'小声讲话',cat:'动词'},
  {g:5,term:'下',u:6,w:'take turns',ipa:'/teɪk tɜːnz/',cn:'按顺序来',cat:'动词'},
  {g:5,term:'下',u:1,w:'when',ipa:'/wen/',cn:'什么时候',cat:'副词'},
  {g:5,term:'下',u:1,w:'after',ipa:'/ˈɑːftə(r)/',cn:'在……后',cat:'介词'},
  {g:5,term:'下',u:1,w:'start',ipa:'/stɑːt/',cn:'开始',cat:'动词'},
  {g:5,term:'下',u:1,w:'usually',ipa:'/ˈjuːʒuəli/',cn:'通常',cat:'副词'},
  {g:5,term:'下',u:1,w:'late',ipa:'/leɪt/',cn:'晚；迟',cat:'形容词'},
  {g:5,term:'下',u:2,w:'which',ipa:'/wɪtʃ/',cn:'哪一个',cat:'代词'},
  {g:5,term:'下',u:2,w:'best',ipa:'/best/',cn:'最',cat:'副词'},
  {g:5,term:'下',u:2,w:'snow',ipa:'/snəʊ/',cn:'雪',cat:'自然'},
  {g:5,term:'下',u:2,w:'vacation',ipa:'/veɪˈkeɪʃn/',cn:'假期',cat:'其他'},
  {g:5,term:'下',u:2,w:'leaf',ipa:'/liːf/',cn:'叶子',cat:'植物'},
  {g:5,term:'下',u:2,w:'fall',ipa:'/fɔːl/',cn:'落下',cat:'动词'},
  {g:5,term:'下',u:3,w:'thing',ipa:'/θɪŋ/',cn:'事情',cat:'其他'},
  {g:5,term:'下',u:3,w:'trip',ipa:'/trɪp/',cn:'旅行',cat:'其他'},
  {g:5,term:'下',u:3,w:'year',ipa:'/jɪə(r)/',cn:'年',cat:'时间'},
  {g:5,term:'下',u:3,w:'contest',ipa:'/ˈkɒntest/',cn:'比赛',cat:'其他'},
  {g:5,term:'下',u:3,w:'Thanksgiving',ipa:'/ˌθæŋksˈɡɪvɪŋ/',cn:'感恩节',cat:'其他'},
  {g:5,term:'下',u:3,w:'Christmas',ipa:'/ˈkrɪsməs/',cn:'圣诞节',cat:'其他'},
  {g:5,term:'下',u:3,w:'holiday',ipa:'/ˈhɒlədeɪ/',cn:'节日；假日',cat:'其他'},
  {g:5,term:'下',u:3,w:'few',ipa:'/fjuː/',cn:'不多；很少',cat:'形容词'},
  {g:5,term:'下',u:4,w:'other',ipa:'/ˈʌðə(r)/',cn:'其他',cat:'代词'},
  {g:5,term:'下',u:4,w:'eleventh',ipa:'/ɪˈlevnθ/',cn:'第十一',cat:'序数'},
  {g:5,term:'下',u:4,w:'thirtieth',ipa:'/ˈθɜːtiəθ/',cn:'第三十',cat:'序数'},
  {g:5,term:'下',u:4,w:'show',ipa:'/ʃəʊ/',cn:'展览；展示',cat:'其他'},
  {g:5,term:'下',u:4,w:'work',ipa:'/wɜːk/',cn:'工作',cat:'动词'},
  {g:5,term:'下',u:4,w:'open',ipa:'/ˈəʊpən/',cn:'开着的',cat:'形容词'},
  {g:5,term:'下',u:5,w:'each',ipa:'/iːtʃ/',cn:'每一个',cat:'代词'},
  {g:5,term:'下',u:5,w:'excited',ipa:'/ɪkˈsaɪtɪd/',cn:'兴奋的',cat:'形容词'},
  {g:5,term:'下',u:6,w:'bamboo',ipa:'/ˌbæmˈbuː/',cn:'竹子',cat:'植物'},
  {g:5,term:'下',u:6,w:'its',ipa:'/ɪts/',cn:'它的',cat:'代词'},
  {g:5,term:'下',u:6,w:'anything',ipa:'/ˈeniθɪŋ/',cn:'任何事物',cat:'代词'},
  {g:5,term:'下',u:6,w:'else',ipa:'/els/',cn:'另外；其他',cat:'副词'},
  {g:5,term:'下',u:6,w:'teach',ipa:'/tiːtʃ/',cn:'教',cat:'动词'},
  {g:5,term:'下',u:1,w:'dancing',ipa:'/ˈdɑːnsɪŋ/',cn:'跳舞',cat:'名词'},
  {g:5,term:'下',u:2,w:'go on a picnic',ipa:'/ɡəʊ ɒn ə ˈpɪknɪk/',cn:'去野餐',cat:'动词'},
  {g:5,term:'下',u:2,w:'pick apples',ipa:'/pɪk ˈæplz/',cn:'摘苹果',cat:'动词'},
  {g:5,term:'下',u:2,w:'make a snowman',ipa:'/meɪk ə ˈsnəʊmæn/',cn:'堆雪人',cat:'动词'},
  {g:5,term:'下',u:2,w:'go swimming',ipa:'/ɡəʊ ˈswɪmɪŋ/',cn:'去游泳',cat:'动词'},
  {g:5,term:'下',u:6,w:'show',ipa:'/ʃəʊ/',cn:'展示',cat:'动词'},
  {g:6,term:'上',u:1,w:'science museum',ipa:'/ˈsaɪəns mjuˈziːəm/',cn:'科学博物馆',cat:'场所'},
  {g:6,term:'上',u:1,w:'post office',ipa:'/ˈpəʊst ɒfɪs/',cn:'邮局',cat:'场所'},
  {g:6,term:'上',u:1,w:'bookstore',ipa:'/ˈbʊkstɔː(r)/',cn:'书店',cat:'场所'},
  {g:6,term:'上',u:1,w:'cinema',ipa:'/ˈsɪnəmə/',cn:'电影院',cat:'场所'},
  {g:6,term:'上',u:1,w:'hospital',ipa:'/ˈhɒspɪtl/',cn:'医院',cat:'场所'},
  {g:6,term:'上',u:1,w:'crossing',ipa:'/ˈkrɒsɪŋ/',cn:'十字路口',cat:'场所'},
  {g:6,term:'上',u:1,w:'turn left',ipa:'/tɜːn left/',cn:'左转',cat:'动词'},
  {g:6,term:'上',u:1,w:'turn right',ipa:'/tɜːn raɪt/',cn:'右转',cat:'动词'},
  {g:6,term:'上',u:1,w:'straight',ipa:'/streɪt/',cn:'笔直地',cat:'副词'},
  {g:6,term:'上',u:2,w:'on foot',ipa:'/ɒn fʊt/',cn:'步行',cat:'交通'},
  {g:6,term:'上',u:2,w:'by bus',ipa:'/baɪ bʌs/',cn:'乘公共汽车',cat:'交通'},
  {g:6,term:'上',u:2,w:'by plane',ipa:'/baɪ pleɪn/',cn:'乘飞机',cat:'交通'},
  {g:6,term:'上',u:2,w:'by taxi',ipa:'/baɪ ˈtæksi/',cn:'乘出租车',cat:'交通'},
  {g:6,term:'上',u:2,w:'by ship',ipa:'/baɪ ʃɪp/',cn:'乘轮船',cat:'交通'},
  {g:6,term:'上',u:2,w:'by subway',ipa:'/baɪ ˈsʌbweɪ/',cn:'乘地铁',cat:'交通'},
  {g:6,term:'上',u:2,w:'by train',ipa:'/baɪ treɪn/',cn:'乘火车',cat:'交通'},
  {g:6,term:'上',u:2,w:'by bike',ipa:'/baɪ baɪk/',cn:'骑自行车',cat:'交通'},
  {g:6,term:'上',u:2,w:'slow',ipa:'/sləʊ/',cn:'慢的',cat:'形容词'},
  {g:6,term:'上',u:2,w:'down',ipa:'/daʊn/',cn:'减少；向下',cat:'副词'},
  {g:6,term:'上',u:2,w:'stop',ipa:'/stɒp/',cn:'停下',cat:'动词'},
  {g:6,term:'上',u:2,w:'wait',ipa:'/weɪt/',cn:'等待',cat:'动词'},
  {g:6,term:'上',u:3,w:'visit',ipa:'/ˈvɪzɪt/',cn:'拜访',cat:'动词'},
  {g:6,term:'上',u:3,w:'film',ipa:'/fɪlm/',cn:'电影',cat:'其他'},
  {g:6,term:'上',u:3,w:'see a film',ipa:'/siː ə fɪlm/',cn:'看电影',cat:'动词'},
  {g:6,term:'上',u:3,w:'trip',ipa:'/trɪp/',cn:'旅行',cat:'其他'},
  {g:6,term:'上',u:3,w:'take a trip',ipa:'/teɪk ə trɪp/',cn:'去旅行',cat:'动词'},
  {g:6,term:'上',u:3,w:'supermarket',ipa:'/ˈsuːpəmɑːkɪt/',cn:'超市',cat:'场所'},
  {g:6,term:'上',u:3,w:'evening',ipa:'/ˈiːvnɪŋ/',cn:'晚上',cat:'时间'},
  {g:6,term:'上',u:3,w:'tonight',ipa:'/təˈnaɪt/',cn:'今晚',cat:'时间'},
  {g:6,term:'上',u:3,w:'tomorrow',ipa:'/təˈmɒrəʊ/',cn:'明天',cat:'时间'},
  {g:6,term:'上',u:3,w:'dictionary',ipa:'/ˈdɪkʃənri/',cn:'词典',cat:'书籍'},
  {g:6,term:'上',u:3,w:'comic',ipa:'/ˈkɒmɪk/',cn:'滑稽的',cat:'形容词'},
  {g:6,term:'上',u:3,w:'word',ipa:'/wɜːd/',cn:'单词',cat:'其他'},
  {g:6,term:'上',u:3,w:'postcard',ipa:'/ˈpəʊstkɑːd/',cn:'明信片',cat:'其他'},
  {g:6,term:'上',u:4,w:'pen pal',ipa:'/pen pæl/',cn:'笔友',cat:'人物'},
  {g:6,term:'上',u:4,w:'hobby',ipa:'/ˈhɒbi/',cn:'业余爱好',cat:'其他'},
  {g:6,term:'上',u:4,w:'jasmine',ipa:'/ˈdʒæzmɪn/',cn:'茉莉',cat:'植物'},
  {g:6,term:'上',u:4,w:'idea',ipa:'/aɪˈdɪə/',cn:'想法',cat:'其他'},
  {g:6,term:'上',u:4,w:'amazing',ipa:'/əˈmeɪzɪŋ/',cn:'令人惊奇的',cat:'形容词'},
  {g:6,term:'上',u:4,w:'shall',ipa:'/ʃæl/',cn:'表示征求意见',cat:'情态'},
  {g:6,term:'上',u:4,w:'goal',ipa:'/ɡəʊl/',cn:'射门',cat:'其他'},
  {g:6,term:'上',u:4,w:'join',ipa:'/dʒɔɪn/',cn:'加入',cat:'动词'},
  {g:6,term:'上',u:4,w:'club',ipa:'/klʌb/',cn:'俱乐部',cat:'其他'},
  {g:6,term:'上',u:4,w:'share',ipa:'/ʃeə(r)/',cn:'分享',cat:'动词'},
  {g:6,term:'上',u:5,w:'factory',ipa:'/ˈfæktri/',cn:'工厂',cat:'场所'},
  {g:6,term:'上',u:5,w:'worker',ipa:'/ˈwɜːkə(r)/',cn:'工人',cat:'职业'},
  {g:6,term:'上',u:5,w:'postman',ipa:'/ˈpəʊstmən/',cn:'邮递员',cat:'职业'},
  {g:6,term:'上',u:5,w:'businessman',ipa:'/ˈbɪznəsmən/',cn:'商人',cat:'职业'},
  {g:6,term:'上',u:5,w:'police officer',ipa:'/pəˈliːs ˈɒfɪsə(r)/',cn:'警察',cat:'职业'},
  {g:6,term:'上',u:5,w:'fisherman',ipa:'/ˈfɪʃəmən/',cn:'渔民',cat:'职业'},
  {g:6,term:'上',u:5,w:'scientist',ipa:'/ˈsaɪəntɪst/',cn:'科学家',cat:'职业'},
  {g:6,term:'上',u:5,w:'pilot',ipa:'/ˈpaɪlət/',cn:'飞行员',cat:'职业'},
  {g:6,term:'上',u:5,w:'coach',ipa:'/kəʊtʃ/',cn:'教练',cat:'职业'},
  {g:6,term:'上',u:5,w:'country',ipa:'/ˈkʌntri/',cn:'国家',cat:'国家'},
  {g:6,term:'上',u:5,w:'sea',ipa:'/siː/',cn:'大海',cat:'自然'},
  {g:6,term:'上',u:5,w:'head teacher',ipa:'/hed ˈtiːtʃə(r)/',cn:'校长',cat:'职业'},
  {g:6,term:'上',u:6,w:'angry',ipa:'/ˈæŋɡri/',cn:'生气的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'afraid',ipa:'/əˈfreɪd/',cn:'害怕',cat:'形容词'},
  {g:6,term:'上',u:6,w:'sad',ipa:'/sæd/',cn:'难过的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'worried',ipa:'/ˈwʌrid/',cn:'担心的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'happy',ipa:'/ˈhæpi/',cn:'高兴的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'see a doctor',ipa:'/siː ə ˈdɒktə(r)/',cn:'看病',cat:'动词'},
  {g:6,term:'上',u:6,w:'wear',ipa:'/weə(r)/',cn:'穿',cat:'动词'},
  {g:6,term:'上',u:6,w:'more',ipa:'/mɔː(r)/',cn:'更多的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'deep',ipa:'/diːp/',cn:'深的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'breath',ipa:'/breθ/',cn:'呼吸',cat:'其他'},
  {g:6,term:'上',u:6,w:'take a deep breath',ipa:'/teɪk ə diːp breθ/',cn:'深深吸一口气',cat:'动词'},
  {g:6,term:'上',u:6,w:'count',ipa:'/kaʊnt/',cn:'数数',cat:'动词'},
  {g:6,term:'上',u:6,w:'chase',ipa:'/tʃeɪs/',cn:'追赶',cat:'动词'},
  {g:6,term:'上',u:1,w:'left',ipa:'/left/',cn:'左',cat:'副词'},
  {g:6,term:'上',u:1,w:'right',ipa:'/raɪt/',cn:'右',cat:'副词'},
  {g:6,term:'上',u:1,w:'ask',ipa:'/ɑːsk/',cn:'问',cat:'动词'},
  {g:6,term:'上',u:1,w:'interesting',ipa:'/ˈɪntrəstɪŋ/',cn:'有趣的',cat:'形容词'},
  {g:6,term:'上',u:1,w:'restaurant',ipa:'/ˈrestrɒnt/',cn:'餐馆',cat:'场所'},
  {g:6,term:'上',u:1,w:'get',ipa:'/ɡet/',cn:'到达',cat:'动词'},
  {g:6,term:'上',u:1,w:'follow',ipa:'/ˈfɒləʊ/',cn:'跟着',cat:'动词'},
  {g:6,term:'上',u:2,w:'early',ipa:'/ˈɜːli/',cn:'早到的',cat:'形容词'},
  {g:6,term:'上',u:2,w:'helmet',ipa:'/ˈhelmet/',cn:'头盔',cat:'其他'},
  {g:6,term:'上',u:2,w:'must',ipa:'/mʌst/',cn:'必须',cat:'情态'},
  {g:6,term:'上',u:2,w:'attention',ipa:'/əˈtenʃn/',cn:'注意',cat:'其他'},
  {g:6,term:'上',u:2,w:'fast',ipa:'/fɑːst/',cn:'快的',cat:'形容词'},
  {g:6,term:'上',u:3,w:'lesson',ipa:'/ˈlesn/',cn:'课',cat:'其他'},
  {g:6,term:'上',u:3,w:'space',ipa:'/speɪs/',cn:'太空',cat:'其他'},
  {g:6,term:'上',u:3,w:'travel',ipa:'/ˈtrævl/',cn:'旅行',cat:'动词'},
  {g:6,term:'上',u:3,w:'price',ipa:'/praɪs/',cn:'价格',cat:'其他'},
  {g:6,term:'上',u:3,w:'together',ipa:'/təˈɡeðə(r)/',cn:'一起',cat:'副词'},
  {g:6,term:'上',u:3,w:'mooncake',ipa:'/ˈmuːnkeɪk/',cn:'月饼',cat:'其他'},
  {g:6,term:'上',u:4,w:'studies',ipa:'/ˈstʌdiz/',cn:'学习（第三人称单数）',cat:'动词'},
  {g:6,term:'上',u:4,w:'puzzle',ipa:'/ˈpʌzl/',cn:'谜',cat:'其他'},
  {g:6,term:'上',u:4,w:'hiking',ipa:'/ˈhaɪkɪŋ/',cn:'远足',cat:'运动'},
  {g:6,term:'上',u:5,w:'university',ipa:'/ˌjuːnɪˈvɜːsəti/',cn:'大学',cat:'场所'},
  {g:6,term:'上',u:5,w:'reporter',ipa:'/rɪˈpɔːtə(r)/',cn:'记者',cat:'职业'},
  {g:6,term:'上',u:5,w:'secretary',ipa:'/ˈsekrətri/',cn:'秘书',cat:'职业'},
  {g:6,term:'上',u:5,w:'use',ipa:'/juːz/',cn:'使用',cat:'动词'},
  {g:6,term:'上',u:5,w:'type',ipa:'/taɪp/',cn:'打字',cat:'动词'},
  {g:6,term:'上',u:6,w:'mice',ipa:'/maɪs/',cn:'老鼠（复数）',cat:'动物'},
  {g:6,term:'上',u:6,w:'bad',ipa:'/bæd/',cn:'坏的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'hurt',ipa:'/hɜːt/',cn:'受伤',cat:'动词'},
  {g:6,term:'上',u:6,w:'ill',ipa:'/ɪl/',cn:'生病的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'wrong',ipa:'/rɒŋ/',cn:'不对的',cat:'形容词'},
  {g:6,term:'上',u:6,w:'feel',ipa:'/fiːl/',cn:'感觉',cat:'动词'},
  {g:6,term:'上',u:6,w:'well',ipa:'/wel/',cn:'健康',cat:'形容词'},
  {g:6,term:'上',u:6,w:'pull',ipa:'/pʊl/',cn:'拉',cat:'动词'},
  {g:6,term:'上',u:1,w:'science',ipa:'/ˈsaɪəns/',cn:'科学',cat:'学科'},
  {g:6,term:'上',u:1,w:'museum',ipa:'/mjuˈziːəm/',cn:'博物馆',cat:'场所'},
  {g:6,term:'上',u:1,w:'go straight',ipa:'/ɡəʊ streɪt/',cn:'直走',cat:'动词'},
  {g:6,term:'上',u:2,w:'slow down',ipa:'/sləʊ daʊn/',cn:'减速',cat:'动词'},
  {g:6,term:'上',u:3,w:'comic book',ipa:'/ˈkɒmɪk bʊk/',cn:'连环画',cat:'书'},
  {g:6,term:'上',u:3,w:'word book',ipa:'/wɜːd bʊk/',cn:'单词书',cat:'书'},
  {g:6,term:'上',u:4,w:'singing',ipa:'/ˈsɪŋɪŋ/',cn:'唱歌',cat:'名词'},
  {g:6,term:'上',u:4,w:'reading stories',ipa:'/ˈriːdɪŋ ˈstɔːriz/',cn:'读故事',cat:'动词'},
  {g:6,term:'上',u:4,w:'playing football',ipa:'/ˈpleɪɪŋ ˈfʊtbɔːl/',cn:'踢足球',cat:'动词'},
  {g:6,term:'上',u:4,w:'doing kung fu',ipa:'/ˈduːɪŋ ˌkʌŋ ˈfuː/',cn:'练武术',cat:'动词'},
  {g:6,term:'上',u:4,w:'cooking',ipa:'/ˈkʊkɪŋ/',cn:'烹饪',cat:'名词'},
  {g:6,term:'上',u:6,w:'count to ten',ipa:'/kaʊnt tə ten/',cn:'数到十',cat:'动词'},
  {g:6,term:'下',u:1,w:'younger',ipa:'/ˈjʌŋɡə(r)/',cn:'更年轻的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'older',ipa:'/ˈəʊldə(r)/',cn:'更年长的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'taller',ipa:'/ˈtɔːlə(r)/',cn:'更高的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'shorter',ipa:'/ˈʃɔːtə(r)/',cn:'更矮的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'longer',ipa:'/ˈlɒŋɡə(r)/',cn:'更长的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'thinner',ipa:'/ˈθɪnə(r)/',cn:'更瘦的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'heavier',ipa:'/ˈheviə(r)/',cn:'更重的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'bigger',ipa:'/ˈbɪɡə(r)/',cn:'更大的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'smaller',ipa:'/ˈsmɔːlə(r)/',cn:'更小的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'stronger',ipa:'/ˈstrɒŋɡə(r)/',cn:'更强壮的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'lower',ipa:'/ˈləʊə(r)/',cn:'更低',cat:'形容词'},
  {g:6,term:'下',u:1,w:'smarter',ipa:'/ˈsmɑːtə(r)/',cn:'更聪明的',cat:'形容词'},
  {g:6,term:'下',u:1,w:'shadow',ipa:'/ˈʃædəʊ/',cn:'影子',cat:'自然'},
  {g:6,term:'下',u:2,w:'cleaned',ipa:'/kliːnd/',cn:'打扫（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'washed',ipa:'/wɒʃt/',cn:'洗（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'watched',ipa:'/wɒtʃt/',cn:'看（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'had',ipa:'/hæd/',cn:'有（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'slept',ipa:'/slept/',cn:'睡觉（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'read',ipa:'/red/',cn:'读（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'saw',ipa:'/sɔː/',cn:'看见（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'went',ipa:'/went/',cn:'去（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'went camping',ipa:'/went ˈkæmpɪŋ/',cn:'去野营',cat:'动词'},
  {g:6,term:'下',u:2,w:'fish',ipa:'/fɪʃ/',cn:'钓鱼',cat:'动词'},
  {g:6,term:'下',u:2,w:'rode',ipa:'/rəʊd/',cn:'骑（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'hurt',ipa:'/hɜːt/',cn:'受伤（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'ate',ipa:'/eɪt/',cn:'吃（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'took',ipa:'/tʊk/',cn:'拍照（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'bought',ipa:'/bɔːt/',cn:'买（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'gift',ipa:'/ɡɪft/',cn:'礼物',cat:'其他'},
  {g:6,term:'下',u:3,w:'went fishing',ipa:'/went ˈfɪʃɪŋ/',cn:'去钓鱼',cat:'动词'},
  {g:6,term:'下',u:3,w:'rode a horse',ipa:'/rəʊd ə hɔːs/',cn:'骑马',cat:'动词'},
  {g:6,term:'下',u:3,w:'rode a bike',ipa:'/rəʊd ə baɪk/',cn:'骑自行车',cat:'动词'},
  {g:6,term:'下',u:3,w:'went swimming',ipa:'/went ˈswɪmɪŋ/',cn:'去游泳',cat:'动词'},
  {g:6,term:'下',u:3,w:'took pictures',ipa:'/tʊk ˈpɪktʃəz/',cn:'照相',cat:'动词'},
  {g:6,term:'下',u:3,w:'bought gifts',ipa:'/bɔːt ɡɪfts/',cn:'买礼物',cat:'动词'},
  {g:6,term:'下',u:3,w:'fell off',ipa:'/fel ɒf/',cn:'从……跌落',cat:'动词'},
  {g:6,term:'下',u:3,w:'Labour Day',ipa:'/ˈleɪbə deɪ/',cn:'劳动节',cat:'其他'},
  {g:6,term:'下',u:3,w:'mule',ipa:'/mjuːl/',cn:'骡子',cat:'动物'},
  {g:6,term:'下',u:3,w:'Turpan',ipa:'/ˈtʊrpɑːn/',cn:'吐鲁番',cat:'地名'},
  {g:6,term:'下',u:3,w:'could',ipa:'/kʊd/',cn:'能（过去式）',cat:'情态'},
  {g:6,term:'下',u:3,w:'till',ipa:'/tɪl/',cn:'直到',cat:'连词'},
  {g:6,term:'下',u:3,w:'beach',ipa:'/biːtʃ/',cn:'海滩',cat:'自然'},
  {g:6,term:'下',u:3,w:'basket',ipa:'/ˈbɑːskɪt/',cn:'篮',cat:'其他'},
  {g:6,term:'下',u:3,w:'part',ipa:'/pɑːt/',cn:'角色',cat:'其他'},
  {g:6,term:'下',u:3,w:'licked',ipa:'/lɪkt/',cn:'舔（过去式）',cat:'动词'},
  {g:6,term:'下',u:3,w:'laughed',ipa:'/lɑːft/',cn:'笑（过去式）',cat:'动词'},
  {g:6,term:'下',u:4,w:'dining hall',ipa:'/ˈdaɪnɪŋ hɔːl/',cn:'饭厅',cat:'场所'},
  {g:6,term:'下',u:4,w:'grass',ipa:'/ɡrɑːs/',cn:'草坪',cat:'自然'},
  {g:6,term:'下',u:4,w:'gym',ipa:'/dʒɪm/',cn:'体育馆',cat:'场所'},
  {g:6,term:'下',u:4,w:'ago',ipa:'/əˈɡəʊ/',cn:'以前',cat:'副词'},
  {g:6,term:'下',u:4,w:'cycling',ipa:'/ˈsaɪklɪŋ/',cn:'骑自行车运动',cat:'运动'},
  {g:6,term:'下',u:4,w:'go cycling',ipa:'/ɡəʊ ˈsaɪklɪŋ/',cn:'去骑自行车',cat:'动词'},
  {g:6,term:'下',u:4,w:'ice-skate',ipa:'/ˈaɪs skeɪt/',cn:'滑冰',cat:'动词'},
  {g:6,term:'下',u:4,w:'badminton',ipa:'/ˈbædmɪntən/',cn:'羽毛球',cat:'运动'},
  {g:6,term:'下',u:1,w:'both',ipa:'/bəʊθ/',cn:'两个都',cat:'代词'},
  {g:6,term:'下',u:1,w:'kilogram',ipa:'/ˈkɪləɡræm/',cn:'千克',cat:'其他'},
  {g:6,term:'下',u:1,w:'become',ipa:'/bɪˈkʌm/',cn:'变成',cat:'动词'},
  {g:6,term:'下',u:2,w:'last',ipa:'/lɑːst/',cn:'上一个',cat:'形容词'},
  {g:6,term:'下',u:2,w:'weekend',ipa:'/ˌwiːkˈend/',cn:'周末',cat:'时间'},
  {g:6,term:'下',u:2,w:'drank',ipa:'/dræŋk/',cn:'喝（过去式）',cat:'动词'},
  {g:6,term:'下',u:2,w:'better',ipa:'/ˈbetə(r)/',cn:'更好的',cat:'形容词'},
  {g:6,term:'下',u:2,w:'faster',ipa:'/ˈfɑːstə(r)/',cn:'更快的',cat:'形容词'},
  {g:6,term:'下',u:2,w:'hotel',ipa:'/həʊˈtel/',cn:'旅馆',cat:'场所'},
  {g:6,term:'下',u:2,w:'stay',ipa:'/steɪ/',cn:'停留',cat:'动词'},
  {g:6,term:'下',u:3,w:'where',ipa:'/weə(r)/',cn:'在哪里',cat:'副词'},
  {g:6,term:'下',u:3,w:'what',ipa:'/wɒt/',cn:'什么',cat:'代词'},
  {g:6,term:'下',u:3,w:'how',ipa:'/haʊ/',cn:'怎样',cat:'副词'},
  {g:6,term:'下',u:4,w:'star',ipa:'/stɑː(r)/',cn:'星',cat:'自然'},
  {g:6,term:'下',u:4,w:'easy',ipa:'/ˈiːzi/',cn:'容易的',cat:'形容词'},
  {g:6,term:'下',u:4,w:'Internet',ipa:'/ˈɪntənet/',cn:'互联网',cat:'其他'},
  {g:6,term:'下',u:4,w:'different',ipa:'/ˈdɪfrənt/',cn:'不同的',cat:'形容词'},
  {g:6,term:'下',u:4,w:'active',ipa:'/ˈæktɪv/',cn:'积极的',cat:'形容词'},
  {g:6,term:'下',u:4,w:'dream',ipa:'/driːm/',cn:'梦',cat:'其他'},
  {g:6,term:'下',u:2,w:'washed my clothes',ipa:'/wɒʃt maɪ kləʊðz/',cn:'洗衣服',cat:'动词'},
  {g:6,term:'下',u:2,w:'stayed at home',ipa:'/steɪd ət həʊm/',cn:'待在家',cat:'动词'},
  {g:6,term:'下',u:2,w:'watched TV',ipa:'/wɒtʃt ˌtiː ˈviː/',cn:'看电视',cat:'动词'},
  {g:6,term:'下',u:2,w:'read a book',ipa:'/red ə bʊk/',cn:'读书',cat:'动词'},
  {g:6,term:'下',u:2,w:'saw a film',ipa:'/sɔː ə fɪlm/',cn:'看电影',cat:'动词'},
  {g:6,term:'下',u:2,w:'had a cold',ipa:'/hæd ə kəʊld/',cn:'感冒',cat:'动词'},
  {g:6,term:'下',u:2,w:'last weekend',ipa:'/lɑːst ˌwiːkˈend/',cn:'上周末',cat:'时间'},
  {g:6,term:'下',u:3,w:'went camping',ipa:'/went ˈkæmpɪŋ/',cn:'去露营',cat:'动词'},
  {g:6,term:'下',u:3,w:'hurt my foot',ipa:'/hɜːt maɪ fʊt/',cn:'伤到脚',cat:'动词'},
  {g:6,term:'下',u:3,w:'ate fresh food',ipa:'/eɪt freʃ fuːd/',cn:'吃新鲜食物',cat:'动词'},
  {g:6,term:'下',u:3,w:'took a bus',ipa:'/tʊk ə bʌs/',cn:'乘公交',cat:'动词'},
];

/* ===================== 课文(Let's talk) ===================== */
window.PEP_TEXTS = [
  // 三上
  {g:3,term:'上',u:1,title:"Let's talk",lines:[
    {role:'Miss White',en:'Hello! I’m Miss White.',cn:'你好！我是怀特老师。'},
    {role:'Wu Yifan',en:'Hello! I’m Wu Yifan.',cn:'你好！我是吴一凡。'},
    {role:'Sarah',en:'Hi! I’m Sarah.',cn:'嗨！我是萨拉。'} ]},
  {g:3,term:'上',u:2,title:"Let's talk",lines:[
    {role:'Mr Jones',en:'Good morning, Miss Green.',cn:'早上好，格林小姐。'},
    {role:'Miss Green',en:'Good morning.',cn:'早上好。'},
    {role:'Mr Jones',en:'This is Miss White.',cn:'这是怀特小姐。'},
    {role:'Miss White',en:'Nice to meet you.',cn:'很高兴见到你。'} ]},
  {g:3,term:'上',u:3,title:"Let's talk",lines:[
    {role:'Mike',en:'How are you?',cn:'你好吗？'},
    {role:'Chen Jie',en:'I’m fine, thank you.',cn:'我很好，谢谢你。'},
    {role:'Mike',en:'Look at me!',cn:'看我！'},
    {role:'Chen Jie',en:'Very well, thanks.',cn:'很好，谢谢。'} ]},
  {g:3,term:'上',u:4,title:"Let's talk",lines:[
    {role:'Mike',en:'What’s this?',cn:'这是什么？'},
    {role:'Chen Jie',en:'It’s a duck.',cn:'它是一只鸭子。'},
    {role:'Mike',en:'What’s that?',cn:'那是什么？'},
    {role:'Chen Jie',en:'It’s a panda.',cn:'它是一只熊猫。'} ]},
  {g:3,term:'上',u:5,title:"Let's talk",lines:[
    {role:'Mike',en:'I’d like some juice, please.',cn:'请给我些果汁。'},
    {role:'Sarah',en:'Here you are.',cn:'给你。'},
    {role:'Mike',en:'Thanks.',cn:'谢谢。'} ]},
  {g:3,term:'上',u:6,title:"Let's talk",lines:[
    {role:'Sam',en:'How old are you?',cn:'你几岁了？'},
    {role:'John',en:'I’m six years old.',cn:'我六岁了。'},
    {role:'Sam',en:'How many plates?',cn:'几个盘子？'} ]},
  // 三下
  {g:3,term:'下',u:1,title:"Let's talk",lines:[
    {role:'Amy',en:'Boys and girls, we have a new friend today.',cn:'孩子们，今天我们有位新朋友。'},
    {role:'Amy',en:'Hi! I’m Amy. I’m from the UK.',cn:'嗨！我是艾米。我来自英国。'},
    {role:'Wang Tong',en:'Welcome!',cn:'欢迎！'} ]},
  {g:3,term:'下',u:2,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'Who’s that man?',cn:'那个男人是谁？'},
    {role:'Amy',en:'He’s my father.',cn:'他是我爸爸。'},
    {role:'Wu Yifan',en:'Is she your mother?',cn:'她是你妈妈吗？'},
    {role:'Amy',en:'Yes, she is.',cn:'是的，她是。'} ]},
  {g:3,term:'下',u:3,title:"Let's talk",lines:[
    {role:'Miss White',en:'Look at that monkey. It’s fat!',cn:'看那只猴子。它好胖！'},
    {role:'Amy',en:'It has a long tail.',cn:'它有一条长尾巴。'},
    {role:'Zhang Peng',en:'It’s tall and thin.',cn:'它又高又瘦。'} ]},
  {g:3,term:'下',u:4,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'Where is my pencil box?',cn:'我的铅笔盒在哪儿？'},
    {role:'John',en:'It’s in your desk.',cn:'它在你的书桌里。'},
    {role:'Zhang Peng',en:'Where is my ruler?',cn:'我的尺子在哪儿？'},
    {role:'John',en:'It’s under the chair!',cn:'它在椅子下面！'} ]},
  {g:3,term:'下',u:5,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'Do you like pears?',cn:'你喜欢梨吗？'},
    {role:'Sarah',en:'Yes, I do.',cn:'是的，我喜欢。'},
    {role:'Zhang Peng',en:'Do you like oranges?',cn:'你喜欢橙子吗？'},
    {role:'Sarah',en:'No, I don’t.',cn:'不，我不喜欢。'} ]},
  {g:3,term:'下',u:6,title:"Let's talk",lines:[
    {role:'Amy',en:'How many kites do you see?',cn:'你看见多少个风筝？'},
    {role:'John',en:'I see twelve.',cn:'我看见十二个。'},
    {role:'Amy',en:'The black one is a bird!',cn:'黑色的那个是只鸟！'} ]},
  // 四上
  {g:4,term:'上',u:1,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'Let’s clean the classroom!',cn:'我们打扫教室吧！'},
    {role:'Zhang Peng',en:'OK.',cn:'好。'},
    {role:'Zhang Peng',en:'Where is it?',cn:'它在哪儿？'},
    {role:'Wu Yifan',en:'It’s near the window.',cn:'它在窗户旁边。'} ]},
  {g:4,term:'上',u:2,title:"Let's talk",lines:[
    {role:'Amy',en:'What’s in your schoolbag?',cn:'你书包里有什么？'},
    {role:'Chen Jie',en:'An English book, a maths book…',cn:'一本英语书、一本数学书……'},
    {role:'Amy',en:'What colour is it?',cn:'它是什么颜色的？'},
    {role:'Chen Jie',en:'It’s blue and white.',cn:'它是蓝白相间的。'} ]},
  {g:4,term:'上',u:3,title:"Let's talk",lines:[
    {role:'John',en:'I have a good friend.',cn:'我有一个好朋友。'},
    {role:'Mike',en:'What’s his name?',cn:'他叫什么名字？'},
    {role:'John',en:'His name is Zhang Peng.',cn:'他叫张鹏。'},
    {role:'John',en:'He’s tall and strong.',cn:'他又高又壮。'} ]},
  {g:4,term:'上',u:4,title:"Let's talk",lines:[
    {role:'Sarah',en:'Where’s Amy? Is she in the study?',cn:'艾米在哪儿？她在书房吗？'},
    {role:'Chen Jie',en:'No, she isn’t.',cn:'不，她不在。'},
    {role:'Sarah',en:'Is she in the kitchen?',cn:'她在厨房吗？'},
    {role:'Chen Jie',en:'Yes, she is.',cn:'是的，她在。'} ]},
  {g:4,term:'上',u:5,title:"Let's talk",lines:[
    {role:'Mike',en:'What would you like?',cn:'你想吃什么？'},
    {role:'Dad',en:'I’d like some soup and bread.',cn:'我想要些汤和面包。'},
    {role:'Mike',en:'Help yourself.',cn:'随便吃吧。'} ]},
  {g:4,term:'上',u:6,title:"Let's talk",lines:[
    {role:'Chen Jie',en:'How many people are there in your family?',cn:'你家有几口人？'},
    {role:'Amy',en:'Three.',cn:'三口。'},
    {role:'Chen Jie',en:'My family has six people.',cn:'我家有六口人。'} ]},
  // 四下
  {g:4,term:'下',u:1,title:"Let's talk",lines:[
    {role:'Amy',en:'Where’s the teachers’ office?',cn:'教师办公室在哪儿？'},
    {role:'Wu Yifan',en:'It’s on the second floor.',cn:'它在二楼。'},
    {role:'Amy',en:'Is this the teachers’ office?',cn:'这是教师办公室吗？'},
    {role:'Wu Yifan',en:'No, it isn’t.',cn:'不，不是。'} ]},
  {g:4,term:'下',u:2,title:"Let's talk",lines:[
    {role:'John',en:'What time is it?',cn:'几点了？'},
    {role:'Wu Yifan',en:'It’s 9 o’clock.',cn:'九点了。'},
    {role:'John',en:'It’s time for English class.',cn:'该上英语课了。'} ]},
  {g:4,term:'下',u:3,title:"Let's talk",lines:[
    {role:'Mark',en:'What’s the weather like in London?',cn:'伦敦天气怎么样？'},
    {role:'Chen Jie',en:'It’s rainy.',cn:'是雨天。'},
    {role:'Mark',en:'Is it cold?',cn:'冷吗？'},
    {role:'Chen Jie',en:'No, it isn’t.',cn:'不冷。'} ]},
  {g:4,term:'下',u:4,title:"Let's talk",lines:[
    {role:'Mike',en:'What are those?',cn:'那些是什么？'},
    {role:'Farmer',en:'They’re sheep.',cn:'是绵羊。'},
    {role:'Mike',en:'Are they horses?',cn:'它们是马吗？'},
    {role:'Farmer',en:'No, they aren’t.',cn:'不，不是。'} ]},
  {g:4,term:'下',u:5,title:"Let's talk",lines:[
    {role:'Sarah',en:'Are these yours?',cn:'这些是你的吗？'},
    {role:'Mike',en:'No, they aren’t.',cn:'不，不是。'},
    {role:'Sarah',en:'Whose coat is this?',cn:'这是谁的外套？'},
    {role:'Mike',en:'It’s mine.',cn:'是我的。'} ]},
  {g:4,term:'下',u:6,title:"Let's talk",lines:[
    {role:'Assistant',en:'Can I help you?',cn:'我能为您做点什么？'},
    {role:'John',en:'The gloves are nice.',cn:'这双手套很漂亮。'},
    {role:'John',en:'How much are they?',cn:'多少钱？'},
    {role:'Assistant',en:'They’re ten yuan.',cn:'十元。'} ]},
  // 五上
  {g:5,term:'上',u:1,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'Who’s your English teacher?',cn:'你的英语老师是谁？'},
    {role:'Oliver',en:'Mr Li.',cn:'李老师。'},
    {role:'Wu Yifan',en:'What’s he like?',cn:'他是什么样的人？'},
    {role:'Oliver',en:'He’s very funny.',cn:'他很滑稽。'} ]},
  {g:5,term:'上',u:2,title:"Let's talk",lines:[
    {role:'John',en:'What do you have on Thursdays?',cn:'星期四你们有什么课？'},
    {role:'Grandpa',en:'I have maths, English and music.',cn:'我有数学、英语和音乐。'},
    {role:'John',en:'Do you often read books?',cn:'你经常看书吗？'},
    {role:'Grandpa',en:'No, I don’t.',cn:'不，我不常看。'} ]},
  {g:5,term:'上',u:3,title:"Let's talk",lines:[
    {role:'Father',en:'What would you like to eat?',cn:'你想吃什么？'},
    {role:'Zhang Peng',en:'A sandwich, please.',cn:'请给我一个三明治。'},
    {role:'Father',en:'What would you like to drink?',cn:'你想喝什么？'},
    {role:'Zhang Peng',en:'I’d like some water.',cn:'我想要些水。'} ]},
  {g:5,term:'上',u:4,title:"Let's talk",lines:[
    {role:'Mr Ma',en:'What can you do, John?',cn:'约翰，你会做什么？'},
    {role:'John',en:'I can sing English songs.',cn:'我会唱英文歌。'},
    {role:'Mr Ma',en:'Can you do any kung fu?',cn:'你会武术吗？'},
    {role:'John',en:'Yes, I can.',cn:'是的，我会。'} ]},
  {g:5,term:'上',u:5,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'There is a big bed.',cn:'有一张大床。'},
    {role:'Sarah',en:'There is a nice photo, too.',cn:'还有一张漂亮的照片。'},
    {role:'Zhang Peng',en:'Where is the ball?',cn:'球在哪儿？'},
    {role:'Sarah',en:'It’s in front of the dog.',cn:'在狗的前面。'} ]},
  {g:5,term:'上',u:6,title:"Let's talk",lines:[
    {role:'Miss White',en:'Is there a river in the park?',cn:'公园里有河吗？'},
    {role:'Zhang Peng',en:'Yes, there is.',cn:'是的，有。'},
    {role:'Miss White',en:'Is there a lake?',cn:'有湖吗？'},
    {role:'Zhang Peng',en:'No, there isn’t.',cn:'不，没有。'} ]},
  // 五下
  {g:5,term:'下',u:1,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'When do you finish class in the morning?',cn:'你们上午什么时候下课？'},
    {role:'Pedro',en:'We finish class at 1 o’clock.',cn:'我们一点下课。'},
    {role:'Zhang Peng',en:'When do you go back to school?',cn:'你什么时候回学校？'},
    {role:'Pedro',en:'At 2:30.',cn:'两点半。'} ]},
  {g:5,term:'下',u:2,title:"Let's talk",lines:[
    {role:'Mike',en:'Which season do you like best?',cn:'你最喜欢哪个季节？'},
    {role:'Wu Yifan',en:'Winter.',cn:'冬天。'},
    {role:'Mike',en:'Why?',cn:'为什么？'},
    {role:'Wu Yifan',en:'Because I can play in the snow.',cn:'因为我可以在雪里玩。'} ]},
  {g:5,term:'下',u:3,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'When is Tree Planting Day?',cn:'植树节是什么时候？'},
    {role:'Mr White',en:'It’s in March.',cn:'在三月。'},
    {role:'Zhang Peng',en:'When is the school trip?',cn:'学校旅行是什么时候？'},
    {role:'Mr White',en:'It’s in May.',cn:'在五月。'} ]},
  {g:5,term:'下',u:4,title:"Let's talk",lines:[
    {role:'Zhang Peng',en:'When is April Fool’s Day?',cn:'愚人节是什么时候？'},
    {role:'Mr Jones',en:'It’s on April 1st.',cn:'在四月一日。'},
    {role:'Zhang Peng',en:'When is your birthday?',cn:'你的生日是什么时候？'},
    {role:'Mr Jones',en:'My birthday is on April 4th.',cn:'我的生日在四月四日。'} ]},
  {g:5,term:'下',u:5,title:"Let's talk",lines:[
    {role:'Sam',en:'Whose dog is it?',cn:'这是谁的狗？'},
    {role:'Chen Jie',en:'It’s mine.',cn:'是我的。'},
    {role:'Sam',en:'Are these all ours?',cn:'这些都是我们的吗？'},
    {role:'Chen Jie',en:'Yes, they are.',cn:'是的。'} ]},
  {g:5,term:'下',u:6,title:"Let's talk",lines:[
    {role:'Tom',en:'What are they doing?',cn:'他们在做什么？'},
    {role:'John',en:'They’re eating lunch.',cn:'他们在吃午饭。'},
    {role:'Tom',en:'What’s the little monkey doing?',cn:'那只小猴子在做什么？'},
    {role:'John',en:'It’s playing with its mother!',cn:'它在和妈妈玩！'} ]},
  // 六上
  {g:6,term:'上',u:1,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'Where is the museum shop?',cn:'博物馆商店在哪儿？'},
    {role:'Robin',en:'It’s near the door.',cn:'在门附近。'},
    {role:'Wu Yifan',en:'How can we get there?',cn:'我们怎么到那儿？'},
    {role:'Robin',en:'Turn left at the bookstore.',cn:'在书店左转。'} ]},
  {g:6,term:'上',u:2,title:"Let's talk",lines:[
    {role:'Mike',en:'How do you come to school?',cn:'你怎么来学校？'},
    {role:'Amy',en:'Usually I come on foot.',cn:'通常我步行来。'},
    {role:'Mike',en:'That’s good exercise.',cn:'那是很好的锻炼。'} ]},
  {g:6,term:'上',u:3,title:"Let's talk",lines:[
    {role:'Mike',en:'What are you going to do tomorrow?',cn:'明天你打算做什么？'},
    {role:'Sarah',en:'I’m going to have an art lesson.',cn:'我打算上美术课。'},
    {role:'Mike',en:'Sounds great!',cn:'听起来很棒！'} ]},
  {g:6,term:'上',u:4,title:"Let's talk",lines:[
    {role:'Peter',en:'What are your hobbies?',cn:'你的爱好是什么？'},
    {role:'Zhang Peng',en:'I like reading stories.',cn:'我喜欢读故事。'},
    {role:'Zhang Peng',en:'Does he live in China?',cn:'他住在中国吗？'},
    {role:'Peter',en:'No, he doesn’t.',cn:'不，他不住在中国。'} ]},
  {g:6,term:'上',u:5,title:"Let's talk",lines:[
    {role:'Hu Bin',en:'What does your father do?',cn:'你爸爸是做什么的？'},
    {role:'Oliver',en:'He’s a businessman.',cn:'他是商人。'},
    {role:'Hu Bin',en:'Where does he work?',cn:'他在哪儿工作？'},
    {role:'Oliver',en:'He works at sea.',cn:'他在海上工作。'} ]},
  {g:6,term:'上',u:6,title:"Let's talk",lines:[
    {role:'Sarah',en:'What’s wrong?',cn:'怎么了？'},
    {role:'Sam',en:'I’m ill.',cn:'我病了。'},
    {role:'Sarah',en:'You should see a doctor.',cn:'你应该去看医生。'},
    {role:'Sam',en:'Don’t be sad.',cn:'别难过。'} ]},
  // 六下
  {g:6,term:'下',u:1,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'How tall are you?',cn:'你有多高？'},
    {role:'John',en:'I’m 1.61 metres.',cn:'我 1.61 米。'},
    {role:'Wu Yifan',en:'Who is taller?',cn:'谁更高？'},
    {role:'John',en:'You’re taller.',cn:'你更高。'} ]},
  {g:6,term:'下',u:2,title:"Let's talk",lines:[
    {role:'Mike',en:'What did you do last weekend?',cn:'上周末你做了什么？'},
    {role:'Chen Jie',en:'I cleaned my room.',cn:'我打扫了房间。'},
    {role:'Mike',en:'Did you watch TV?',cn:'你看电视了吗？'},
    {role:'Chen Jie',en:'No, I didn’t.',cn:'不，我没看。'} ]},
  {g:6,term:'下',u:3,title:"Let's talk",lines:[
    {role:'Amy',en:'Where did you go over your holiday?',cn:'假期你去哪儿了？'},
    {role:'John',en:'I went to Xinjiang.',cn:'我去了新疆。'},
    {role:'Amy',en:'What did you do there?',cn:'你在那儿做了什么？'},
    {role:'John',en:'I rode a horse.',cn:'我骑了马。'} ]},
  {g:6,term:'下',u:4,title:"Let's talk",lines:[
    {role:'Wu Yifan',en:'There was no library in my old school.',cn:'我以前的学校没有图书馆。'},
    {role:'Grandpa',en:'Tell us about your school, please.',cn:'请给我们讲讲你的学校。'},
    {role:'Wu Yifan',en:'Before, I was quiet.',cn:'以前，我很安静。'} ]}
];

/* ===================== 重点句型 ===================== */
window.PEP_PATTERNS = [
  // 三上
  {g:3,term:'上',u:1,focus:'问候与自我介绍',pattern:'Hello! / Hi!  I’m …',examples:['Hello! I’m Mike.','Hi! I’m Chen Jie.'],cn:'你好！/ 嗨！我是……'},
  {g:3,term:'上',u:1,focus:'询问姓名',pattern:'What’s your name?  My name’s …',examples:['What’s your name?','My name’s John.'],cn:'你叫什么名字？我叫……'},
  {g:3,term:'上',u:2,focus:'介绍他人',pattern:'This is …',examples:['This is Miss Green.','This is my friend.'],cn:'这是……'},
  {g:3,term:'上',u:2,focus:'表达问候',pattern:'Good morning / afternoon!',examples:['Good morning, Miss White.','Good afternoon, Mr Jones.'],cn:'早上/下午好！'},
  {g:3,term:'上',u:3,focus:'询问身体状况',pattern:'How are you?  I’m fine, thank you.',examples:['How are you?','I’m fine, thank you.'],cn:'你好吗？我很好，谢谢。'},
  {g:3,term:'上',u:3,focus:'指示与描述',pattern:'Look at …  It’s …',examples:['Look at me!','It’s a red nose.'],cn:'看……。它是……'},
  {g:3,term:'上',u:4,focus:'询问近处/远处事物',pattern:'What’s this / that?  It’s a …',examples:['What’s this?','It’s a duck.','What’s that?','It’s a panda.'],cn:'这/那是什么？它是……'},
  {g:3,term:'上',u:5,focus:'表达饮食意愿',pattern:'I’d like some …  Here you are.',examples:['I’d like some juice.','Here you are.'],cn:'我想要些……。给你。'},
  {g:3,term:'上',u:5,focus:'提供食物',pattern:'Have some …',examples:['Have some bread.','Have some eggs.'],cn:'吃些……吧。'},
  {g:3,term:'上',u:6,focus:'询问年龄',pattern:'How old are you?  I’m … years old.',examples:['How old are you?','I’m six years old.'],cn:'你几岁？我……岁。'},
  {g:3,term:'上',u:6,focus:'询问数量',pattern:'How many …?',examples:['How many plates?','How many books?'],cn:'多少个……？'},
  // 三下
  {g:3,term:'下',u:1,focus:'介绍来源',pattern:'I’m from …  We have a new friend.',examples:['I’m from the UK.','We have a new friend today.'],cn:'我来自……。我们今天有位新朋友。'},
  {g:3,term:'下',u:1,focus:'询问来源',pattern:'Where are you from?',examples:['Where are you from?','I’m from China.'],cn:'你来自哪里？'},
  {g:3,term:'下',u:2,focus:'询问身份',pattern:'Who’s that man / woman?  He’s / She’s …',examples:['Who’s that man?','He’s my father.'],cn:'那个男人/女人是谁？他是/她是……'},
  {g:3,term:'下',u:2,focus:'确认关系',pattern:'Is she / he your …?  Yes, … / No, …',examples:['Is she your mother?','Yes, she is.'],cn:'她/他是你的……吗？是的/不是。'},
  {g:3,term:'下',u:3,focus:'描述外形',pattern:'It’s (so) tall / fat / thin …',examples:['It’s so tall!','It’s fat and short.'],cn:'它（那么）高/胖/瘦……'},
  {g:3,term:'下',u:3,focus:'描述特征',pattern:'It has a / an …',examples:['It has a long nose.','It has big eyes.'],cn:'它有……'},
  {g:3,term:'下',u:4,focus:'询问位置',pattern:'Where is …?  It’s in / on / under …',examples:['Where is my ruler?','It’s under the chair.'],cn:'……在哪儿？它在……里/上/下。'},
  {g:3,term:'下',u:5,focus:'表达喜好',pattern:'Do you like …?  Yes, I do. / No, I don’t.',examples:['Do you like pears?','Yes, I do.'],cn:'你喜欢……吗？是的，我喜欢/不，我不喜欢。'},
  {g:3,term:'下',u:5,focus:'陈述喜好',pattern:'I like … / I don’t like …',examples:['I like apples.','I don’t like bananas.'],cn:'我喜欢……/我不喜欢……'},
  {g:3,term:'下',u:6,focus:'询问所见数量',pattern:'How many … do you see?  I see …',examples:['How many kites do you see?','I see twelve.'],cn:'你看见多少个……？我看见……'},
  {g:3,term:'下',u:6,focus:'询问拥有数量',pattern:'How many … do you have?',examples:['How many crayons do you have?','I have sixteen.'],cn:'你有多少个……？'},
  // 四上
  {g:4,term:'上',u:1,focus:'提议与方位',pattern:'Let’s …  Where is it?',examples:['Let’s clean the classroom!','Where is it?'],cn:'我们……吧！它在哪儿？'},
  {g:4,term:'上',u:2,focus:'询问物品',pattern:'What’s in your …?  What colour is it?',examples:['What’s in your schoolbag?','It’s blue and white.'],cn:'你的……里有什么？它是什么颜色的？'},
  {g:4,term:'上',u:3,focus:'询问姓名与特征',pattern:'What’s his / her name?  He’s / She’s …',examples:['What’s his name?','His name is Zhang Peng.'],cn:'他/她叫什么名字？他/她……'},
  {g:4,term:'上',u:3,focus:'描述外貌',pattern:'He / She is …  He / She has …',examples:['He’s tall and strong.','She has long hair.'],cn:'他/她是……他/她有……'},
  {g:4,term:'上',u:4,focus:'询问位置(人)',pattern:'Is she / he in the …?  Yes / No.',examples:['Is she in the kitchen?','Yes, she is.'],cn:'她/他在……里吗？是的/不是。'},
  {g:4,term:'上',u:5,focus:'表达用餐意愿',pattern:'What would you like?  I’d like …',examples:['What would you like?','I’d like some soup.'],cn:'你想吃什么？我想要……'},
  {g:4,term:'上',u:5,focus:'礼貌用语',pattern:'Help yourself.  Would you like …?',examples:['Help yourself.','Would you like a knife?'],cn:'随便吃吧。你想要……吗？'},
  {g:4,term:'上',u:6,focus:'询问家庭人数',pattern:'How many people are there in your family?',examples:['How many people are there in your family?','Three.'],cn:'你家有几口人？'},
  {g:4,term:'上',u:6,focus:'询问职业',pattern:'What’s your …’s job?  He’s / She’s a …',examples:['What’s your father’s job?','He’s a doctor.'],cn:'你……是做什么工作的？他/她是……'},
  // 四下
  {g:4,term:'下',u:1,focus:'询问地点与楼层',pattern:'Where’s the …?  It’s on the … floor.',examples:['Where’s the library?','It’s on the first floor.'],cn:'……在哪儿？它在……楼。'},
  {g:4,term:'下',u:2,focus:'询问时间',pattern:'What time is it?  It’s …',examples:['What time is it?','It’s 9 o’clock.'],cn:'几点了？……点。'},
  {g:4,term:'下',u:2,focus:'该做某事',pattern:'It’s time for / to …',examples:['It’s time for English class.','It’s time to go to school.'],cn:'该……了。'},
  {g:4,term:'下',u:3,focus:'询问天气',pattern:'What’s the weather like …?  It’s …',examples:['What’s the weather like in Beijing?','It’s sunny.'],cn:'……天气怎么样？是……'},
  {g:4,term:'下',u:3,focus:'请求许可',pattern:'Can I go outside?  Yes / No.',examples:['Can I go outside?','No, you can’t.'],cn:'我能出去吗？可以/不行。'},
  {g:4,term:'下',u:4,focus:'询问复数事物',pattern:'What are these / those?  They’re …',examples:['What are those?','They’re sheep.'],cn:'这些/那些是什么？它们是……'},
  {g:4,term:'下',u:4,focus:'确认复数',pattern:'Are they …?  Yes / No.',examples:['Are they horses?','No, they aren’t.'],cn:'它们是……吗？是的/不是。'},
  {g:4,term:'下',u:5,focus:'询问所属',pattern:'Whose … is this?  It’s … / Are these …?',examples:['Whose coat is this?','It’s mine.'],cn:'这是谁的……？是……/这些是……吗？'},
  {g:4,term:'下',u:6,focus:'购物用语',pattern:'Can I help you?  How much is / are …?',examples:['Can I help you?','How much is it?'],cn:'我能为您做点什么？……多少钱？'},
  // 五上
  {g:5,term:'上',u:1,focus:'询问人物特征',pattern:'What’s he / she like?  He’s / She’s …',examples:['What’s she like?','She’s kind.'],cn:'他/她是什么样的人？他/她……'},
  {g:5,term:'上',u:2,focus:'询问课程',pattern:'What do you have on …?',examples:['What do you have on Mondays?','I have Chinese and English.'],cn:'……你们有什么课？'},
  {g:5,term:'上',u:2,focus:'询问频率',pattern:'Do you often …?  Yes / No.',examples:['Do you often read books?','No, I don’t.'],cn:'你经常……吗？是的/不是。'},
  {g:5,term:'上',u:3,focus:'询问饮食意愿',pattern:'What would you like to eat / drink?',examples:['What would you like to eat?','A sandwich, please.'],cn:'你想吃/喝什么？'},
  {g:5,term:'上',u:4,focus:'询问能力',pattern:'What can you do?  I can …  Can you …?',examples:['What can you do?','I can sing.','Can you dance?'],cn:'你会做什么？我会……你会……吗？'},
  {g:5,term:'上',u:5,focus:'there be 单数',pattern:'There is …  Where is …?',examples:['There is a big bed.','Where is the cat?'],cn:'有…………在哪儿？'},
  {g:5,term:'上',u:5,focus:'方位介词',pattern:'in front of / between / above / beside / behind',examples:['It’s in front of the dog.','The ball is under the table.'],cn:'在……前面/之间/上面/旁边/后面'},
  {g:5,term:'上',u:6,focus:'there be 疑问',pattern:'Is there …?  Yes / No.',examples:['Is there a river?','Yes, there is.'],cn:'有……吗？是的/没有。'},
  {g:5,term:'上',u:6,focus:'Are there 复数',pattern:'Are there any …?',examples:['Are there any lakes?','No, there aren’t.'],cn:'有……吗（复数）？'},
  // 五下
  {g:5,term:'下',u:1,focus:'询问时间(日常)',pattern:'When do you …?  I … at …',examples:['When do you get up?','I get up at 6:30.'],cn:'你什么时候……？我……点……'},
  {g:5,term:'下',u:2,focus:'询问喜好季节',pattern:'Which season do you like best?  Why?  Because …',examples:['Which season do you like best?','Winter.','Why?','Because it’s white.'],cn:'你最喜欢哪个季节？为什么？因为……'},
  {g:5,term:'下',u:3,focus:'询问日期(节日)',pattern:'When is …?  It’s in …',examples:['When is Tree Planting Day?','It’s in March.'],cn:'……是什么时候？在……月。'},
  {g:5,term:'下',u:4,focus:'询问具体日期',pattern:'When is …?  It’s on …',examples:['When is your birthday?','It’s on April 4th.'],cn:'……是什么时候？在……（具体日期）。'},
  {g:5,term:'下',u:5,focus:'名词性物主代词',pattern:'Whose … is this?  It’s mine / yours / his …',examples:['Whose dog is it?','It’s mine.'],cn:'这是谁的……？是我的/你的/他的……'},
  {g:5,term:'下',u:6,focus:'现在进行时',pattern:'What are you / they doing?  I’m / They’re …ing',examples:['What are they doing?','They’re eating lunch.'],cn:'你/他们在做什么？我/他们正在……'},
  {g:5,term:'下',u:6,focus:'公共规则',pattern:'Talk quietly.  Keep your desk clean.',examples:['Talk quietly, please.','Keep your desk clean.'],cn:'小声说话。保持桌面整洁。'},
  // 六上
  {g:6,term:'上',u:1,focus:'问路与指路',pattern:'Where is …?  How can I get to …?  Turn left / right.',examples:['Where is the cinema?','Turn left at the bookstore.'],cn:'……在哪儿？我怎么到……？左转/右转。'},
  {g:6,term:'上',u:2,focus:'出行方式',pattern:'How do you come to school?  I come … by … / on foot',examples:['How do you come to school?','I come by bus.','Usually I come on foot.'],cn:'你怎么来学校？我乘……/步行来。'},
  {g:6,term:'上',u:2,focus:'交通规则',pattern:'Slow down and stop …  Stop and wait …',examples:['Slow down and stop at a yellow light.','Stop and wait at a red light.'],cn:'黄灯减速停/红灯停下等。'},
  {g:6,term:'上',u:3,focus:'一般将来时(打算)',pattern:"What are you going to do?  I'm going to …",examples:['What are you going to do tomorrow?','I’m going to see a film.'],cn:'你打算做什么？我打算……'},
  {g:6,term:'上',u:3,focus:'将来时间',pattern:'When are you going?  next / tomorrow / tonight',examples:['When are you going?','Next Wednesday.'],cn:'你什么时候去？'},
  {g:6,term:'上',u:4,focus:'询问爱好',pattern:'What are your hobbies?  I like …ing',examples:['What are your hobbies?','I like singing.'],cn:'你的爱好是什么？我喜欢……'},
  {g:6,term:'上',u:4,focus:'第三人称习惯',pattern:'Does he / she …?  Yes / No.',examples:['Does he live in China?','No, he doesn’t.'],cn:'他/她……吗？是的/不是。'},
  {g:6,term:'上',u:5,focus:'询问职业',pattern:'What does he / she do?  He’s / She’s a …',examples:['What does your father do?','He’s a doctor.'],cn:'他/她是做什么的？他/她是……'},
  {g:6,term:'上',u:5,focus:'询问工作地点',pattern:'Where does he / she work?  He / She works …',examples:['Where does he work?','He works at sea.'],cn:'他/她在哪里工作？'},
  {g:6,term:'上',u:6,focus:'询问感受',pattern:'What’s wrong?  How do you feel?  I’m …',examples:['What’s wrong?','I’m ill.','How do you feel?','I’m sad.'],cn:'怎么了？你感觉怎么样？我……'},
  {g:6,term:'上',u:6,focus:'建议',pattern:'You should …  Don’t …',examples:['You should see a doctor.','Don’t be sad.'],cn:'你应该……。别……。'},
  // 六下
  {g:6,term:'下',u:1,focus:'比较级(身高)',pattern:'How tall are you?  I’m … metres.  Who is taller?',examples:['How tall are you?','I’m 1.61 metres.','Who is taller?'],cn:'你多高？我……米。谁更高？'},
  {g:6,term:'下',u:1,focus:'比较级(年龄/体型)',pattern:'…-er than …',examples:['You’re older than me.','I’m taller than this one.'],cn:'……比……更……'},
  {g:6,term:'下',u:2,focus:'一般过去时',pattern:'What did you do …?  I …ed / went / …',examples:['What did you do last weekend?','I cleaned my room.'],cn:'……你做了什么？我……（过去式）'},
  {g:6,term:'下',u:2,focus:'过去时一般疑问',pattern:'Did you …?  Yes / No.',examples:['Did you watch TV?','No, I didn’t.'],cn:'你……了吗？是的/不是。'},
  {g:6,term:'下',u:3,focus:'过去时(地点)',pattern:'Where did you go?  What did you do there?',examples:['Where did you go?','I went to Xinjiang.','What did you do there?','I rode a horse.'],cn:'你去哪儿了？你在那儿做了什么？'},
  {g:6,term:'下',u:4,focus:'There be 过去式',pattern:'There was / were (no) …',examples:['There was no library.','There were no computers.'],cn:'（以前）有/没有……'},
  {g:6,term:'下',u:4,focus:'今昔对比',pattern:'Before, I was …  Now, I’m …',examples:['Before, I was quiet.','Now, I’m active.'],cn:'以前我……，现在我很……'}
];